### ISSUE TITLE
Autoscroll is not working always

### ISSUE THREAD

**Issue by kinex** [diegoveloper/flutter_keyboard_actions#101]
I have a form where only some of edit fields have a visible action bar. In Android this makes sense since Android keyboard already has next/done -buttons. I use action bar in Android only for displaying suggestions in specific fields.

There is a problem that autoscroll does not work if previous field does not have the action bar visible. Sample code to reproduce the issue:

```dart
import 'package:flutter/material.dart';
import 'package:keyboard_actions/keyboard_actions.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _focusNodePrice = FocusNode();
  final _focusNodeQuantity = FocusNode();

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    return Scaffold(
      appBar: AppBar(
        title: Text("KeyboardActions"),
      ),
      body: Padding(
        padding: const EdgeInsets.only(top: 15.0, left: 15.0, right: 15.0),
        child: Center(
          child: Theme(
            data: Theme.of(context).copyWith(
              disabledColor: Colors.blue,
              iconTheme: IconTheme.of(context).copyWith(
                color: Colors.red,
                size: 35,
              ),
            ),
            child: KeyboardActions(
              tapOutsideToDismiss: false,
              autoScroll: true,
              config: KeyboardActionsConfig(
                keyboardSeparatorColor: Colors.purple,
                actions: [
                  KeyboardActionsItem(
                    focusNode: _focusNodePrice,
                    displayActionBar: false,
                  ),
                  KeyboardActionsItem(
                    focusNode: _focusNodeQuantity,
                  ),
                ],
              ),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  SizedBox(
                    height: size.height / 2,
                    child: FlutterLogo(),
                  ),
                  TextField(
                    textInputAction: TextInputAction.next,
                    keyboardType: TextInputType.number,
                    focusNode: _focusNodePrice,
                    decoration: InputDecoration(
                      labelText: "Unit price",
                    ),
                    onSubmitted: (value) => FocusScope.of(context).nextFocus(),
                  ),
                  SizedBox(
                    height: 16,
                  ),
                  TextField(
                    focusNode: _focusNodeQuantity,
                    keyboardType: TextInputType.number,
                    decoration: InputDecoration(
                      labelText: "Quantity",
                    ),
                  ),
                  SizedBox(
                    height: 400,
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```
In my test device (Galaxy S7/Android 8), the "Quantity" field is left partially behind the action bar when it should be scrolled in view. In my real app, the whole field is left behind the action bar (I could not reproduce the exact same case with the sample app).

**Comment by diegoveloper** [comment]
I pushed new changes on `dev` branch, there is a new property for `KeyboardActions`, is `disableScroll` , set this to true, and let me know if it works.

Update your `pubspec.yaml` to my git repo and `deb` branch.

**Comment by kinex** [comment]
I tried that but it didn't have any effect, same issue. To clarify the issue, there is not only one text field where I want to use `KeyboardActions` but there can be many of them. The point is that there are also text fields where I don't need `KeyboardActions` at all and in that case this issue happens.

**Comment by diegoveloper** [comment]
I tried with the sample you sent and it's working fine,  did you set `disableScroll` true ?

**Comment by kinex** [comment]
Yes I did set it to `true`. I also had to change `Column` to `ListView` due to layout errors shown in screen ("bottom overflowed...").

But I don't even understand what are you trying to achieve with this new property `disableScroll`. It doesn't sound correct. I think the scrolling should not be disabled. It should just work even if not all text fields have an action bar visible.

**Comment by diegoveloper** [comment]
oh sorry, wrong issue, I thought it was this : https://github.com/diegoveloper/flutter_keyboard_actions/issues/100  , sorry, yeah I'll need to check this issue.

**Comment by kinex** [comment]
Ok, no problem :) Please check this when you have time and let me know if you need more info.

**Comment by diegoveloper** [comment]
I sent a new push to `dev` branch , could you try again ? don't forget to run `flutter pub upgrade`, (point to my github and dev branch), let me know if it works for you.

**Comment by kinex** [comment]
After a quick test it seems to work now. Thanks for the fix!
