### ISSUE TITLE
The method 'setKeyboardActions' isn't defined for the type 'KeyboardActions'.

### ISSUE THREAD

**Issue by stoneshower** [diegoveloper/flutter_keyboard_actions#104]
https://pub.dev/packages/keyboard_actions/changelog#310-breaking-change
I see `FormKeyboardActions was renamed to KeyboardActions` but when I try to use   `KeyboardActions.setKeyboardActions`, i got an error which says 
The method 'setKeyboardActions' isn't defined for the type 'KeyboardActions'.

``` dart
KeyboardActions.setKeyboardActions(context, _buildConfig(context));
```

I guess it is not just renamed but this method was removed in the update.
I could not find the docs about it, does anybody know how to handle this issue?

**Comment by diegoveloper** [comment]
Check the samples https://github.com/diegoveloper/flutter_keyboard_actions/tree/master/example/lib
