### ISSUE TITLE
keyboard_custom.dart WidgetBuilder 

### ISSUE THREAD

**Issue by mrchenmo** [diegoveloper/flutter_keyboard_actions#106]
There is a WidgetBuilder defined in keyboard custom.dart which caused me to conflict when import'package:keyboard_actions/keyboard_actions.dart' and framework.dart at the same time. I had to hide the WidgetBuilder in keyboard custom.dart

**Comment by diegoveloper** [comment]
I'll work on this

**Comment by diegoveloper** [comment]
check the latest version
