### ISSUE TITLE
improvement: disable next/previous buttons when none exists

### ISSUE THREAD

**Issue by jayjwarrick** [diegoveloper/flutter_keyboard_actions#11]
The up/down arrows could be disabled when there's no next or previous focusNode to go to.

This would look like this:
<img width="291" alt="Screen Shot 2019-05-09 at 4 23 23 PM" src="https://user-images.githubusercontent.com/3268245/57492723-ce0a4e00-7276-11e9-962f-ef198ff609c4.png">

@diegoveloper I'll send a PR if this sounds good! I'm planning on using this lib in production so will be getting lots of little improvements hopefully.

**Comment by diegoveloper** [comment]
Sure! Go ahead. Thanks
