### ISSUE TITLE
1.22: Keyboard disappears

### ISSUE THREAD

**Issue by shredding** [diegoveloper/flutter_keyboard_actions#115]
I just had to downgrade back to 1.20.4 because on android the keyboard directly disappears after opening. I assume that has to do with this new soft keyboard, but I couldn't figure it out.

**Comment by diegoveloper** [comment]
Check the latest version :). `3.3.1`

**Comment by shredding** [comment]
You rock!

**Comment by kinex** [comment]
I guess I have this issue. As an additional note all affected users seem to have a Pixel device. I cannot see this issue in my Galaxy S7.

**Comment by diegoveloper** [comment]
Did you try the latest version?

**Comment by kinex** [comment]
I seem to have 3.3.0+1 currently. Unfortunately I upgraded my app a couple of days too early so I didn't see this update.

**Comment by diegoveloper** [comment]
Try 3.3.1
