### ISSUE TITLE
Custom keyboard with SafeArea

### ISSUE THREAD

**Issue by simicn** [diegoveloper/flutter_keyboard_actions#117]
When I run the `example` which clone from the  latest `master`.

Found  that custom keyboard didn't work with SafeArea in `iPhone 11 Pro Max` simulator.
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-06 at 14 18 37](https://user-images.githubusercontent.com/902283/95165607-ecafa400-07de-11eb-8142-2449d1d3946f.png)

After I add SafeArea to `NumericKeyboard`, it doesn't work very well.
![image](https://user-images.githubusercontent.com/902283/95164946-98f08b00-07dd-11eb-8b28-c8231c504bf9.png)

**Comment by diegoveloper** [comment]
Can you increase the size of the height? Maybe adding the MediaQuery
padding bottom

**Comment by simicn** [comment]
Will adding SafeArea affect the height of keyboard?

**Comment by simicn** [comment]
Already tried, thanks for your reply.
