### ISSUE TITLE
KeyboardActions cannot be used with a Form

### ISSUE THREAD

**Issue by TheManuz** [diegoveloper/flutter_keyboard_actions#118]
`KeyboardActions` cannot be used in the same tree of a `Form`, because it gives the following exception:

```
RenderBox was not laid out: _RenderSingleChildViewport#607cd relayoutBoundary=up14 NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1785 pos 12: 'hasSize'
The relevant error-causing widget was
    KeyboardActions 
```

But since `KeyboardActions` doesn't extend `Form`, `Form` functions cannot be used anymore.

I used a `Key` for my form, needed for `formKey.currentState.validate()`, to validate the whole Form before submitting, and this is not possible when using `KeyboardActions`.

**Comment by diegoveloper** [comment]
Use KeyboardActions above Form widget

**Comment by diegoveloper** [comment]
does it works for you? otherwise try adding a simple code to reproduce the issue.
