### ISSUE TITLE
Getting the size of the displayed keyboard.

### ISSUE THREAD

**Issue by danhadv** [diegoveloper/flutter_keyboard_actions#119]
First let me send kudos for a really nice widget.  Very helpful!

I'm using the widget in kind of a weird situation.  I build a simple number scroller to match my design and of course I want a way to "enter" a number instead of having to scroll.  I have everything working just right with one exception.  I need to scroll so that my spinner is completely in view.   Simple enough but the problem is that I"m using a "Flutter_sliding_up_panel" and a singleScrollView widget to hold my custom spinner.  

The result of this is that when the keyboard is displayed the MediaQuery.of(context).edgeInset.bottom is always 0. I'm "guessing" this is probably due to the way I'm using the Keyboard_Action widget inside the slide up panel.  But it would be hard to move it the widget tree.

With all that said, I have the view inside my panel scrolling right to where I want it when I "know" the height of the keyboard.  So all I need to "fix" my problem is a way to know the exact height of the keyboard widget when it is displayed.  I'm wondering if the height is the same across devices/screen sizes.  In my limited testing it looks like it is the same size and not some percentage of the screen, but I could be wrong on that.

I know I haven't really provided any code samples, way too much crap to have it make sense.  I do not think this is a bug in any way.  My question is more along the lines of is there any way for me to know the height of the keyboard?  If I had this value my "backwards" way of scrolling the panel will work just fine.

Thoughts?

**Comment by diegoveloper** [comment]
Hey, thanks for your words, currently there is no way to get the height of the keyboard from my package, but check this answer, maybe you need an additional plugin : https://stackoverflow.com/a/61380451/666221
