### ISSUE TITLE
Not working with iPhone SE 2nd Generation (iOS 14) simulator

### ISSUE THREAD

**Issue by HugoHeneault** [diegoveloper/flutter_keyboard_actions#126]
Hi there! Your example works fine on android or other iOS simulators, but it is not working on iPhone SE 2nd Generation on iOS 14...

The keyboard doesn't show up and the whole app freezes (even hot restart won't work after that, full rebuild is required)

Any ideas why?

Thanks! 🙏

**Comment by diegoveloper** [comment]
hmm no idea, try a `flutter clean` first and attach a video if it's possible.
Don't forget to run `flutter doctor` and add the log here.

**Comment by HugoHeneault** [comment]
Weird I rebooted the device, ran `flutter clean` and now it works... 

Thanks for your fast answer :)
