### ISSUE TITLE
Action Bar stuck on the bottom of the screen

### ISSUE THREAD

**Issue by FDuhen** [diegoveloper/flutter_keyboard_actions#127]
Hey guys,

I don't know if it can be fixed, but your Android activity's configuration must have 
`android:windowSoftInputMode="adjustResize"`
Otherwise the Action Bar will be stuck on the bottom of the screen and won't be placed above the keyboard

![Screenshot 2020-10-29 at 12 24 27](https://user-images.githubusercontent.com/33631420/97562329-bdf1ab80-19e1-11eb-801a-3053936f9278.png)
![Screenshot 2020-10-29 at 12 24 18](https://user-images.githubusercontent.com/33631420/97562339-c1853280-19e1-11eb-940f-aec62a8dc0f3.png)

**Comment by diegoveloper** [comment]
Hmm, can you add a simple code to reproduce the issue?

**Comment by FDuhen** [comment]
Sure ! 
In the Example Project
Edit the 
android > app > src > main > AndroidManifest.xml

and replace 
`android:windowSoftInputMode="adjustResize"`
by
`android:windowSoftInputMode="stateAlwaysHidden"`
or by 
`android:windowSoftInputMode="adjustPan"`

**Comment by diegoveloper** [comment]
Oh I see, well that's a config from native side, so I don't think we can do anything. Why did you change that config?

**Comment by FDuhen** [comment]
Because I need a keyboard which is showing above the content without resizing the view (the stateAlwaysHidden option)

**Comment by diegoveloper** [comment]
just use this property of the scaffold : https://api.flutter.dev/flutter/material/Scaffold/resizeToAvoidBottomInset.html

**Comment by FDuhen** [comment]
Fixes my problem for now, thank you !
I hope I won't have any other specific case needing for the "adjustResize" value to be changed
