### ISSUE TITLE
How to change the color of the arrow? 

### ISSUE THREAD

**Issue by lucas-livingnet** [diegoveloper/flutter_keyboard_actions#129]
How to change the color of the arrow? It's possible?

![Captura de Tela 2020-11-20 às 14 11 38](https://user-images.githubusercontent.com/62895141/99829026-84bcdf00-2b3a-11eb-978d-a53c7f6c2c4b.png)

**Comment by diegoveloper** [comment]
Check the samples : https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/example/lib/sample.dart

**Comment by lucas-livingnet** [comment]
thanks my friend!
