### ISSUE TITLE
improvement: support custom footer widget

### ISSUE THREAD

**Issue by jaysephjw** [diegoveloper/flutter_keyboard_actions#13]
Hey, so my most recent project has been to add a custom keyboard :) Thought I would open an issue to track if we wanted to support it here. I've been working on a change to allow a KeyboardAction to specify a custom overlay widget. 

 The widget would be shown below below the keyboard action bar. My use case is to implement a custom keyboard, for inputs that don't use the system keyboard, e.g. a color input:

<img width="400" alt="custom_keyboard" src="https://user-images.githubusercontent.com/3268245/57895955-1d1a2b00-7803-11e9-9943-589a4590bf16.png">

It could also be used along with the system keyboard for things like providing some instructions, an error message, or input suggestions.

**Comment by jaysephjw** [comment]
relates to https://github.com/VGVentures/keyboard_avoider/pull/1, which changes keyboard_avoider to also be able to avoid things besides the keyboard. Right now we avoid our keyboard actions bar by adding it as "focusPadding" to keyboard avoider, which is kind of a hack.

**Comment by diegoveloper** [comment]
That would be a nice feature! Thankss
