### ISSUE TITLE
Flutter test

### ISSUE THREAD

**Issue by Lomski** [diegoveloper/flutter_keyboard_actions#135]
Scroll in widget tests (tester.scrollUntilVisible and tester.ensureVisible) and integration tests (driver.scrollUntilVisible and driver.scrollIntoView) doesnt work with SingleChildScrollView widget inside KeyboardActions. But work with ListView widget.

**Comment by alehmazok** [comment]
@Lomski Try to pass `disableScroll: true` or `enable: false` to KeyboardActions widget while testing.
