### ISSUE TITLE
Action Button Color

### ISSUE THREAD

**Issue by sinangokce** [diegoveloper/flutter_keyboard_actions#148]
Thanks for the job! I wanted to know if there is an easy way to change the color of action buttons in the keyboard bar?

Thanks!

**Comment by diegoveloper** [comment]
Yes https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/example/lib/content.dart#L86

**Comment by BenjaminFarquhar** [comment]
`defaultDoneWidget` has since been released which reduces many lines of code. 

```
KeyboardActions(
  tapOutsideBehavior: TapOutsideBehavior.opaqueDismiss,
  config: KeyboardActionsConfig(
    defaultDoneWidget: const Text(
      'Done',
      style: TextStyle(
        color: Colors.black, // Change color here
        fontSize: 16.0,
        fontWeight: FontWeight.w500,
      ),
    ),
```
