### ISSUE TITLE
tabOutsideToDismiss enhancement

### ISSUE THREAD

**Issue by crizant** [diegoveloper/flutter_keyboard_actions#150]
I would like to tap outside to dismiss, at the same time if user tapped on some buttons in the background,
they would also response to the tap.

I think adding an option to change the `behavior` of the transparent overlay to `HitTestBehavior.translucent` would help.

**Comment by diegoveloper** [comment]
well, this is open source you can send a pull request if you want

**Comment by crizant** [comment]
It's strange that I did a clone and changed the HitTestBehavior, it still blocks gestures for the underneath widgets. 🧐

**Comment by crizant** [comment]
Finally I did a refactor and used `Listener` widget which won't cancel the gesture, it works now: #151

**Comment by diegoveloper** [comment]
https://pub.dev/packages/keyboard_actions/versions/3.4.1 ready! , thanks @crizant
