### ISSUE TITLE
BoxConstraints forces an infinite height.

### ISSUE THREAD

**Issue by AKA-LinCoder** [diegoveloper/flutter_keyboard_actions#152]
hi,
i have two SingleChildScrollView,and i have some textfields in there when i use the library ,it does not work  ,
it show BoxConstraints forces an infinite height.how can i fix it。
(when i use one SingleChildScrollView ,it works,but when i use ExpansionPanel,it need two SingleChildScrollView)

**Comment by diegoveloper** [comment]
Add a minimum sample code to reproduce the issue.

**Comment by AKA-LinCoder** [comment]
`import 'package:blast/ui/widgets/my_sroll_view.dart';
import 'package:flutter/gestures.dart';
import "package:flutter/material.dart";
import 'package:flutter/rendering.dart';
import 'package:keyboard_actions/keyboard_actions.dart';
import 'dart:ui';

import 'core/util/other_utils.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return App2();
  }
}

class App2 extends StatefulWidget {
  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App2> with SingleTickerProviderStateMixin {
  // List _page=[Home3(),Home2(),Home4()];
  // int index=0;
  late TabController con;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    con = new TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
    con.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      appBar: AppBar(
        title: Text('test'),
      ),
      body: Home(),
    ));
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  List<int> mList = [];
  List<ExpandState> expandStateList = [];
  final FocusNode _nodeText1 = FocusNode();
  final FocusNode _nodeText2 = FocusNode();
  final FocusNode _nodeText3 = FocusNode();

  void initState() {
    mList.add(0);
    expandStateList.add(ExpandState(0, false));
  }

  KeyboardActionsConfig _buildConfig(BuildContext context) {
    return KeyboardActionsConfig(
      keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
      keyboardBarColor: Colors.grey[200],
      nextFocus: true,
      actions: [],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Container(
        // width: double.infinity,
        child: Center(
      child: SingleChildScrollView(
        child: ExpansionPanelList(
          expansionCallback: (index, bool) {
            //回调
            setState(() {
              expandStateList[index].isOpen = !expandStateList[index].isOpen;
            });
          },
          children: mList.map((index) {
            return ExpansionPanel(
                headerBuilder: (context, isExpanded) {
                  return ListTile(
                    title: Text('head'),
                  );
                },
                body: KeyboardActions(
                  config: _buildConfig(context),
                  child: SingleChildScrollView(
                    child: Container(
                      constraints: BoxConstraints(maxHeight: MediaQuery.of(context).size.height),
                      child: Column(
                        children: [
                          TextField(
                            focusNode: _nodeText1,
                          ),
                          TextField(
                            focusNode: _nodeText2,
                          ),
                          TextField(
                            focusNode: _nodeText3,
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
                ///this is my self ScrollView ,it run like up code 
                // body: MyScrollView(
                //   keyboardConfig: Utils.getKeyboardActionsConfig(context, [_nodeText1,_nodeText2,_nodeText3]),
                //   children: [
                //     TextField(focusNode: _nodeText1,),
                //     TextField(focusNode: _nodeText2,),
                //     TextField(focusNode: _nodeText3,),
                //   ],
                // ),
                isExpanded: expandStateList[index].isOpen);
          }).toList(),
        ),
      ),
    ));
  }
}

class ExpandState {
  var isOpen;
  var index;
  ExpandState(this.index, this.isOpen);
}
`

here is my minimum code,it will show  BoxConstraints forces an infinite height ,

**Comment by diegoveloper** [comment]
Try using a fixed height when you use `ExpansionPanel` : 

```
  @override
  Widget build(BuildContext context) {
    return Container(
// width: double.infinity,
        child: Center(
      child: SingleChildScrollView(
        child: ExpansionPanelList(
          expansionCallback: (index, bool) {
//回调
            setState(() {
              expandStateList[index].isOpen = !expandStateList[index].isOpen;
            });
          },
          children: mList.map((index) {
            return ExpansionPanel(
                headerBuilder: (context, isExpanded) {
                  return ListTile(
                    title: Text('head'),
                  );
                },
                body: SizedBox(
                  height: 200,
                  child: Container(
                    constraints: BoxConstraints(maxHeight: MediaQuery.of(context).size.height),
                    child: KeyboardActions(
                      config: _buildConfig(context),
                      child: Column(
                        children: [
                          TextField(
                            focusNode: _nodeText1,
                          ),
                          TextField(
                            focusNode: _nodeText2,
                          ),
                          TextField(
                            focusNode: _nodeText3,
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
                isExpanded: expandStateList[index].isOpen);
          }).toList(),
        ),
      ),
    ));
  }
}
```

Instead ` height: 200,` you can calculate based on your mediaquery

**Comment by AKA-LinCoder** [comment]
thanks! 
:-）
