### ISSUE TITLE
action bar hides behind the keyboard when the version upgrades from 3.4.0 to 3.4.1

### ISSUE THREAD

**Issue by KevinSu1991** [diegoveloper/flutter_keyboard_actions#153]
here is my sample code
body: Container(
            width: MediaQuery.of(context).size.width,
            height: MediaQuery.of(context).size.height,
            decoration: BoxDecoration(color: Color(0xFF000000)),
            child: SafeArea(child: Consumer<MMMemeTextEditorNotifier>(builder: (context, notifier, child) {
              return SingleChildScrollView(
                child: Column(
                  children: [
                    SizedBox(
                      height: 10,
                    ),
                    Container(
                      height: MediaQuery.of(context).size.height * 0.4,
                      child: KeyboardActions(
                        disableScroll: true,
                        config: _statedKeyboardActionsConfig(notifier: notifier),
                        child: Center(
                          child: Stack(
                            alignment: notifier.memeText.getCurrentStackTextAlign(),
                            children: <Widget>[
                              notifier.memeText.showStroke()
                                  ? Text(
                                      "${notifier.memeText.text}",
                                      textAlign: notifier.memeText.getCurrentTextAlign(),
                                      style: TextStyle(
                                        fontSize: notifier.memeText.fontSize,
                                        fontFamily: notifier.memeText.font,
                                        fontWeight: MMFontsService.getFontWeight(notifier.memeText.fontWeight),
                                        fontStyle: MMFontsService.getFontStyle(notifier.memeText.fontStyle),
                                        color: HexColor.fromHex(notifier.memeText.color),
                                      ),
                                    )
                                  : SizedBox(height: 1),
                              TextField(
                                enableInteractiveSelection: false,
                                focusNode: notifier.normalFocusNode,
                                autofocus: notifier.keyboardFocus,
                                textAlign: notifier.memeText.getCurrentTextAlign(),
                                controller: notifier.textEditingController,
                                decoration: InputDecoration(
                                  // contentPadding: const EdgeInsets.all(5),
                                  border: InputBorder.none,
                                  focusedBorder: InputBorder.none,
                                  enabledBorder: InputBorder.none,
                                  disabledBorder: InputBorder.none,
                                  errorBorder: InputBorder.none,
                                ),
                                textInputAction: TextInputAction.newline,
                                maxLines: null,
                                keyboardType: TextInputType.multiline,
                                style: notifier.getTextFieldTextStyle(),
                              )
                            ],
                          ),
                        ),
                      ),
                    ),
                    KeyboardCustomInput<Color>(
                      focusNode: notifier.colorFocusNode,
                      height: 5,
                      notifier: notusedNotifier,
                      builder: (context, val, hasFocus) {
                        return Container(
                          width: double.maxFinite,
                        );
                      },
                    ),
                  ],
                ),
              );
            })),
          ),

please help me.

**Comment by diegoveloper** [comment]
Please format the code and add some gifs/videos

**Comment by woelmer** [comment]
I have the same problem

**Comment by CBL0123** [comment]
I have the same problem

**Comment by CBL0123** [comment]
![IMG_0143](https://user-images.githubusercontent.com/17310462/127089245-819c3028-32e8-4086-b7ae-3776ae33a6d5.PNG)
![IMG_0142](https://user-images.githubusercontent.com/17310462/127089259-aa519b74-aa83-4357-87df-1618d38566c0.PNG)

**Comment by diegoveloper** [comment]
Can you add a minimum sample code?

**Comment by CBL0123** [comment]
static KeyboardActionsConfig getKeyboardActionsConfig(BuildContext context, List<FocusNode> list) {
    return KeyboardActionsConfig(
      keyboardBarColor: const Color(0xFFF7F7F7),
      nextFocus: true,
      actions: List.generate(
          list.length,
          (i) => KeyboardActionsItem(
                focusNode: list[i],
                toolbarButtons: [
                  (node) {
                    return GestureDetector(
                      onTap: () => node.unfocus(),
                      child: Container(
                        color: Colors.transparent,
                        padding: const EdgeInsets.only(left: 30, right: 16, top: 10, bottom: 10),
                        child: const LoadAssetImage(
                          'common/arrow_down',
                          width: 16,
                        ),
                      ),
                    );
                  },
                ],
              )),
    );
  }

**Comment by CBL0123** [comment]
![0ffaddd-846e-4ad8-bd90-3911464975ee](https://user-images.githubusercontent.com/17310462/127091992-e780b81d-9651-4f1b-9753-579650107066.png)

**Comment by diegoveloper** [comment]
@CBL0123 , Create a minimum sample reproducing the issue and paste the code well formatted here.

**Comment by KevinSu1991** [comment]
> Please format the code and add some gifs/videos

thanks for your replay.

```
Widget build(BuildContext context) {
    return ChangeNotifierProvider.value(
        value: _memeTextEditorNotifier,
        child: Scaffold(
          appBar: AppBar(),
          backgroundColor: Colors.transparent,
          body: Container(
            width: MediaQuery.of(context).size.width,
            height: MediaQuery.of(context).size.height,
            decoration: BoxDecoration(color: Color(0xFF000000)),
            child: SafeArea(child: Consumer<MMMemeTextEditorNotifier>(builder: (context, notifier, child) {
              return SingleChildScrollView(
                child: Column(
                  children: [
                    Container(
                      height: MediaQuery.of(context).size.height * 0.4,
                      child: KeyboardActions(
                        disableScroll: true,
                        config: _statedKeyboardActionsConfig(notifier: notifier),
                        child: Center(
                          child: Stack(
                            alignment: notifier.memeText.getCurrentStackTextAlign(),
                            children: <Widget>[
                              Text(
                                      "${notifier.memeText.text}",
                                      textAlign: notifier.memeText.getCurrentTextAlign(),
                                      style: TextStyle(
                                        fontSize: notifier.memeText.fontSize,
                                        fontFamily: notifier.memeText.font,
                                        fontWeight: MMFontsService.getFontWeight(notifier.memeText.fontWeight),
                                        fontStyle: MMFontsService.getFontStyle(notifier.memeText.fontStyle),
                                        color: HexColor.fromHex(notifier.memeText.color),
                                      ),
                                    ),
                              TextField(
                                enableInteractiveSelection: false,
                                focusNode: notifier.normalFocusNode,
                                autofocus: notifier.keyboardFocus,
                                textAlign: notifier.memeText.getCurrentTextAlign(),
                                controller: notifier.textEditingController,
                                decoration: InputDecoration(
                                  // contentPadding: const EdgeInsets.all(5),
                                  border: InputBorder.none,
                                  focusedBorder: InputBorder.none,
                                  enabledBorder: InputBorder.none,
                                  disabledBorder: InputBorder.none,
                                  errorBorder: InputBorder.none,
                                ),
                                textInputAction: TextInputAction.newline,
                                maxLines: null,
                                keyboardType: TextInputType.multiline,
                                style: notifier.getTextFieldTextStyle(),
                              )
                            ],
                          ),
                        ),
                      ),
                    ),
                    KeyboardCustomInput<Color>(
                      focusNode: notifier.colorFocusNode,
                      height: 5,
                      notifier: notusedNotifier,
                      builder: (context, val, hasFocus) {
                        return Container(
                          width: double.maxFinite,
                        );
                      },
                    ),
                    KeyboardCustomInput<Color>(
                      focusNode: notifier.fontFocusNode,
                      height: 5,
                      notifier: notusedNotifier,
                      builder: (context, val, hasFocus) {
                        return Container(
                          width: double.maxFinite,
                        );
                      },
                    ),
                    KeyboardCustomInput<Color>(
                      focusNode: notifier.captionFocusNode,
                      height: 5,
                      notifier: notusedNotifier,
                      builder: (context, val, hasFocus) {
                        return Container(
                          width: double.maxFinite,
                        );
                      },
                    ),
                    KeyboardCustomInput<Color>(
                      focusNode: notifier.textStrokeFocusNode,
                      height: 5,
                      notifier: notusedNotifier,
                      builder: (context, val, hasFocus) {
                        return Container(
                          width: double.maxFinite,
                        );
                      },
                    ),
                  ],
                ),
              );
            })),
          ),
        ));
  }

  KeyboardActionsConfig _statedKeyboardActionsConfig({required MMMemeTextEditorNotifier notifier}) {
    return KeyboardActionsConfig(
              keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
              keyboardBarColor: Colors.white,
              nextFocus: false,
              actions: [
                KeyboardActionsItem(
                    focusNode: notifier.normalFocusNode,
                    footerBuilder: (_) => TextEditorToolbar(textEditorNotifier: notifier),
                    displayActionBar: false)
              ]);
  }
```

![661627364928_ pic_hd](https://user-images.githubusercontent.com/7909544/127102483-d158062d-61d7-477d-9309-ad332baea65a.jpg)
with the version 3.4.0, it works fine. when i upgrade to 3.4.1, my custom footer always on the bottom of the screen.

**Comment by duykhanhhs1** [comment]
Hey, I can not unfocus by tap Done after open keyboard first time. Anyone can help me?

![image](https://user-images.githubusercontent.com/74110768/127133947-c0619bf8-3309-4cb1-b7e3-3d287a01c4cd.png)

**Comment by diegoveloper** [comment]
Working on it ...!

**Comment by diegoveloper** [comment]
New version released `3.4.2` can anybody confirm that it's working fine?

**Comment by naamapps** [comment]
@diegoveloper 
Working now but we have another problem,
It adds a bar above the actions which hides the main view.
Version 3.4.2.
Here is a video

https://user-images.githubusercontent.com/37176893/127195396-ddd7a3a5-37c2-4e52-bbd5-f0e9736c7721.mp4

**Comment by diegoveloper** [comment]
oh, can you add a minimum code to reproduce that issue?

**Comment by naamapps** [comment]
Sorry @diegoveloper, I can't share the code.
Put some text fields inside of a scaffold with resizeToAvoidBottomInset: true and have the body in a scrollview.
Have a footer for KeyboardActionsItem
```
 KeyboardActionsItem(
                  focusNode: focusNode,
                  displayArrows: false,
                  displayDoneButton: false,
                  displayActionBar: false,
                  footerBuilder: (context) => PreferredSize(
                    preferredSize: const Size.fromHeight(50),
                    child: ....
                  )
```

**Comment by crizant** [comment]
On `keyboard_actions.dart` line 392, assigning 200 to `newOffset` is strange. May be you forgot to remove a debug statement? @diegoveloper

**Comment by diegoveloper** [comment]
> On `keyboard_actions.dart` line 392, assigning 200 to `newOffset` is strange. May be you forgot to remove a debug statement? @diegoveloper

omg! sorry! haha I was very busy/distracted. Thanks, a new version is coming.

**Comment by crizant** [comment]
Btw I have a new bug, let me gather some information then create a new issue.

**Comment by diegoveloper** [comment]
ok, new version is ready `3.4.3`

**Comment by KevinSu1991** [comment]
> ok, new version is ready `3.4.3`

thank you, it works.
