### ISSUE TITLE
Can not unfocus textfield when focus the first time

### ISSUE THREAD

**Issue by duykhanhhs1** [diegoveloper/flutter_keyboard_actions#154]
I can not unfocus text field when click done when I focus it first time, but I can unfocus if I retap the textfield. Please help me!

**Comment by diegoveloper** [comment]
Add a minimum code to reproduce the issue

**Comment by duykhanhhs1** [comment]
class KeyboardActionExample extends StatelessWidget {

  final FocusNode _nodeText1 = FocusNode();

  KeyboardActionsConfig _buildConfig(BuildContext context) {
    return KeyboardActionsConfig(
      keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
      keyboardBarColor: Colors.grey[200],
      nextFocus: true,
      actions: [
        KeyboardActionsItem(
          focusNode: _nodeText1,
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: KeyboardActions(
        config: _buildConfig(context),
        child: Center(
          child: Padding(
            padding: const EdgeInsets.all(15.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: <Widget>[
                TextField(
                  keyboardType: TextInputType.text,
                  focusNode: _nodeText1,
                  decoration: InputDecoration(
                    hintText: "Input text",
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by diegoveloper** [comment]
Did you try ? https://stackoverflow.com/questions/53481261/how-to-unfocus-textfield-that-has-custom-focusnode

**Comment by duykhanhhs1** [comment]
Looks like the text field is not focused on first click. It works when i click again on the textfield

**Comment by duykhanhhs1** [comment]
![image](https://user-images.githubusercontent.com/74110768/127183708-a96f69f8-9729-44f8-9775-f50691a7a0bb.png)
![image](https://user-images.githubusercontent.com/74110768/127183750-ac6c5104-a3e3-428a-9199-2f0ab92f3517.png)
The first and the second click

**Comment by duykhanhhs1** [comment]
> Did you try ? https://stackoverflow.com/questions/53481261/how-to-unfocus-textfield-that-has-custom-focusnode

I tried it before posting the question but it's still the same

**Comment by diegoveloper** [comment]
not sure if I can help you, maybe you could try on stackoverflow

**Comment by duykhanhhs1** [comment]
Hey, I realized it only works with Stateful
