### ISSUE TITLE
Cannot open keyboard again when using TapOutsideBehavior.translucentDismiss

### ISSUE THREAD

**Issue by crizant** [diegoveloper/flutter_keyboard_actions#155]
Steps to reproduce:
1. Run the example app
2. Go to sample 2
3. Tap on the text field to open keyboard
4. Tap on the text field again to dismiss keyboard
5. Tap on the text field again, the keyboard won't pop up

**Comment by diegoveloper** [comment]
@crizant do you have the fix for this?

**Comment by crizant** [comment]
I'm still investigating. 
Currently I did a temporary fix it on my app by wrapping the text field inside an `IngorePointer` widget, when the field has focus, switch the `ignoring` value to `true`.

**Comment by crizant** [comment]
The fix in my app is not suitable for this package, since when there are more than 1 text fields, user may need to tap on different text fields to switch focus.

I can think of 2 solutions:
1. The `Listener` use `HitTestBehavior.opaque` and if the tap is outside the text field, programmatically simulate the tap in the position after dismiss. But that would need the `key` of the text field to calculate widget position.
2. Add focus node listeners. When a node focused again after dismissing within `_timeToDismiss`, which is 100ms, unfocus it.

Haven't tried yet, but what do you think?

**Comment by diegoveloper** [comment]
We are already using focus and focus listeners there.

**Comment by crizant** [comment]
Simply removing `await Future.delayed(_timeToDismiss);` on line 356 of `keyboard_actions.dart` seems to solve the issue.

**Comment by diegoveloper** [comment]
> Simply removing `await Future.delayed(_timeToDismiss);` on line 356 of `keyboard_actions.dart` seems to solve the issue.

hmm can you try if that change break anything? maybe you can avoid that line only for a specific case, I think that delay was intended to simulate the keyboard animation

**Comment by crizant** [comment]
There are too many use cases that I can't test them all. But I've added a completer, so that we can wait for the previous animation to completer before inserting new overlay. #156

**Comment by diegoveloper** [comment]
> There are too many use cases that I can't test them all. But I've added a completer, so that we can wait for the previous animation to complete before inserting new overlay. #156

Thanks, merged

**Comment by crizant** [comment]
When will the next version come out?

**Comment by diegoveloper** [comment]
hmm not sure, do you need this change urgent?

**Comment by crizant** [comment]
Not urgent. Are you waiting for some other enhancement or fix?

**Comment by diegoveloper** [comment]
maybe a few more changes

**Comment by crizant** [comment]
Hi, why you closed the issue but didn't publish a new version? 🧐

**Comment by diegoveloper** [comment]
Hmm wasn't published yet?

**Comment by crizant** [comment]
No, you said you need to do a few more changes.

**Comment by crizant** [comment]
Sorry I missed it. Seems it is published.
