### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by chrisvidal** [diegoveloper/flutter_keyboard_actions#164]
```yaml
dependencies:
    keyboard_actions: ^3.4.4
```

```dart
import 'package:keyboard_actions/keyboard_actions.dart';
```

Package not found; What am I missing here?

**Comment by diegoveloper** [comment]
Try:

flutter clean
flutter pub upgrade

**Comment by chrisvidal** [comment]
thanks @diegoveloper 
but same issue after cleaning

**Comment by diegoveloper** [comment]
@chrisvidal did you find any solution?

**Comment by chrisvidal** [comment]
nope, I had to abandon the idea of using the package for now

**Comment by capemsx** [comment]
This steps helped me:
1. Run `Flutter clean` (as already mentioned)
2. Completely close Android Studio (or whatever IDE you use)
3. Reopen and run `Flutter pub get`

Hope it helps!
