### ISSUE TITLE
improvement: disable the Done button

### ISSUE THREAD

**Issue by frey1esm** [diegoveloper/flutter_keyboard_actions#17]
Would be nice to be able to disable the Done (Go, Next, etc) button as part of some form validation.

**Comment by diegoveloper** [comment]
You can change the `nextFocus` to false to hide the `prev/next` buttons in the `KeyboardActionsConfig`.

Also you can change the `closeWidget` or hide it in your `KeyboardAction` :

```
/// Optional widget to display to the right of the bar
  final Widget closeWidget;

  /// true [default] to display a closeWidget
  final bool displayCloseWidget;
```
