### ISSUE TITLE
KeyBoard Action Bar displays over the bottomsheet.

### ISSUE THREAD

**Issue by SanthoseKumar118** [diegoveloper/flutter_keyboard_actions#171]
keyboard pushes the bottom sheet up, but the action bar stays over the bottom sheet.

**Comment by diegoveloper** [comment]
Add simple code to reproduce the issue

**Comment by SanthoseKumar118** [comment]
<img width="1280" alt="Screenshot 2021-12-24 at 10 36 23 AM" src="https://user-images.githubusercontent.com/81604265/147318832-0c5b52f8-2b3a-43a2-9242-1f7b2c5d9b07.png">
Normally

**Comment by SanthoseKumar118** [comment]
<img width="1280" alt="Screenshot 2021-12-24 at 10 38 04 AM" src="https://user-images.githubusercontent.com/81604265/147318919-97df1c10-778e-42e0-8072-593de59781d9.png">
After adding action Bar

**Comment by diegoveloper** [comment]
Try reproducing the issue in a simple code.

**Comment by SanthoseKumar118** [comment]
I missed your post. I will post a sample code today.

**Comment by SanthoseKumar118** [comment]
import 'package:flutter/material.dart';
import 'customkeyboardactions.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController tecComment = TextEditingController();
  CustomKeyBoard keyBoardNode = CustomKeyBoard();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children:[
          Expanded(child: Container(height: double.infinity,)),
          sendMessage(),
        ],
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
  sendMessage() {
    return Container(height:64,decoration: BoxDecoration(color: Colors.white,border: Border(top: BorderSide(color: Colors.grey,width: 0.6))),
        child: Padding(padding: EdgeInsets.all(9),
            child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween,children: <Widget>[
              Expanded(child: search()),
              SizedBox(width: 10),
              TextButton(onPressed: (){}, child: Text('投稿する', style: TextStyle(fontSize: 14,fontWeight: FontWeight.bold),))
            ])));
  }

  search(){
    return KeyboardActions(
      config: keyBoardNode.buildConfig(context),
      child: Container(height: 44,
          child: TextField(
            focusNode: keyBoardNode.nodeText1,
      decoration: InputDecoration(prefixIconConstraints: BoxConstraints(maxWidth: 33),
          border: OutlineInputBorder(
              borderRadius: BorderRadius.all(Radius.circular(10)),
              borderSide: BorderSide(width: 1, color:Colors.grey.shade50)),
      hintText: "コメントする..."
      )
          )),
    );
  }
}

**Comment by SanthoseKumar118** [comment]
@diegoveloper   import 'package:flutter/material.dart';
import 'customkeyboardactions.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController tecComment = TextEditingController();
  CustomKeyBoard keyBoardNode = CustomKeyBoard();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children:[
          Expanded(child: Container(height: double.infinity,)),
          sendMessage(),
        ],
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
  sendMessage() {
    return Container(height:64,decoration: BoxDecoration(color: Colors.white,border: Border(top: BorderSide(color: Colors.grey,width: 0.6))),
        child: Padding(padding: EdgeInsets.all(9),
            child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween,children: <Widget>[
              Expanded(child: search()),
              SizedBox(width: 10),
              TextButton(onPressed: (){}, child: Text('投稿する', style: TextStyle(fontSize: 14,fontWeight: FontWeight.bold),))
            ])));
  }

  search(){
    return KeyboardActions(
      config: keyBoardNode.buildConfig(context),
      child: Container(height: 44,
          child: TextField(
              focusNode: keyBoardNode.nodeText1,
              decoration: InputDecoration(prefixIconConstraints: BoxConstraints(maxWidth: 33),
                  border: OutlineInputBorder(
                      borderRadius: BorderRadius.all(Radius.circular(10)),
                      borderSide: BorderSide(width: 1, color:Colors.grey.shade50)),
                  hintText: "コメントする..."
              )
          )),
    );
  }
}

**Comment by SanthoseKumar118** [comment]
I have added sample code could you please check it

**Comment by diegoveloper** [comment]
hey try formatting the code use, do you think the issue is similar to this ? https://github.com/diegoveloper/flutter_keyboard_actions/issues/172

**Comment by SanthoseKumar118** [comment]
@diegoveloper No Can you check the above images.
1st image >> Without adding Keyboard Action Bar.
2nd image >> After adding Keyboard Action Bar it lies over the text area. 
Request: I want the Keyboard action bar to push the Bottom sheet on its top.


Sample Code

import 'package:flutter/material.dart';
import 'customkeyboardactions.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController tecComment = TextEditingController();
  CustomKeyBoard keyBoardNode = CustomKeyBoard();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children:[
          Expanded(child: Container(height: double.infinity,)),
          sendMessage(),
        ],
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
  sendMessage() {
    return Container(height:64,decoration: BoxDecoration(color: Colors.white,border: Border(top: BorderSide(color: Colors.grey,width: 0.6))),
        child: Padding(padding: EdgeInsets.all(9),
            child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween,children: <Widget>[
              Expanded(child: search()),
              SizedBox(width: 10),
              TextButton(onPressed: (){}, child: Text('投稿する', style: TextStyle(fontSize: 14,fontWeight: FontWeight.bold),))
            ])));
  }

  search(){
    return KeyboardActions(
      config: keyBoardNode.buildConfig(context),
      child: Container(height: 44,
          child: TextField(
            focusNode: keyBoardNode.nodeText1,
      decoration: InputDecoration(prefixIconConstraints: BoxConstraints(maxWidth: 33),
          border: OutlineInputBorder(
              borderRadius: BorderRadius.all(Radius.circular(10)),
              borderSide: BorderSide(width: 1, color:Colors.grey.shade50)),
      hintText: "コメントする..."
      )
          )),
    );
  }
}

class CustomKeyBoard{
  final FocusNode nodeText1 = FocusNode();
  final FocusNode nodeText2 = FocusNode();
  final FocusNode nodeText3 = FocusNode();
  final FocusNode nodeText4 = FocusNode();
  final FocusNode nodeText5 = FocusNode();
  final FocusNode nodeText6 = FocusNode();
  final FocusNode nodeText7 = FocusNode();
  final FocusNode nodeText8 = FocusNode();
  final FocusNode nodeText9 = FocusNode();

  /// Creates the [KeyboardActionsConfig] to hook up the fields
  /// and their focus nodes to our [FormKeyboardActions].
  KeyboardActionsConfig buildConfig(BuildContext context) {
    return KeyboardActionsConfig(
      keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
      keyboardBarColor: Colors.grey[200],
      nextFocus: true,
      actions: [
        KeyboardActionsItem(enableArrows: false,
          focusNode: nodeText1,
          toolbarButtons: [
                (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Text(
                  "完了",
                  style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
                ),
              );
            }, (node) {
              return SizedBox(width: 20,);
            }
          ],),
        KeyboardActionsItem(focusNode: nodeText2, toolbarButtons: [
              (node) {
            return GestureDetector(
              onTap: () => node.unfocus(),
              child: Text(
                "完了",
                style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
              ),
            );
          },(node) {
            return SizedBox(width: 20,);
          }
        ]),
        KeyboardActionsItem(
          focusNode: nodeText3,
          toolbarButtons: [
                (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Text(
                  "完了",
                  style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
                ),
              );
            }, (node) {
              return SizedBox(width: 20,);
            }
          ],),
        KeyboardActionsItem(
          focusNode: nodeText4,
          toolbarButtons: [
                (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Text(
                  "完了",
                  style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
                ),
              );
            }, (node) {
              return SizedBox(width: 20,);
            }
          ],),
        KeyboardActionsItem(focusNode: nodeText5, toolbarButtons: [
              (node) {
            return GestureDetector(
              onTap: () => node.unfocus(),
              child: Text(
                "完了",
                style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
              ),
            );
          },(node) {
            return SizedBox(width: 20,);
          }
        ]),
        KeyboardActionsItem(
          focusNode: nodeText6,
          //displayCloseWidget: false,
        ),
        KeyboardActionsItem(
          focusNode: nodeText7,
          toolbarButtons: [
            //button 1
                (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Container(
                  color: Colors.white,
                  padding: EdgeInsets.all(8.0),
                  child: Text(
                    "CLOSE",
                    style: TextStyle(color: Colors.black),
                  ),
                ),
              );
            },
            //button 2
                (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Container(
                  color: Colors.black,
                  padding: EdgeInsets.all(8.0),
                  child: Text(
                    "DONE",
                    style: TextStyle(color: Colors.white),
                  ),
                ),
              );
            }
          ],
        ),
        KeyboardActionsItem(
          focusNode: nodeText8,
          footerBuilder: (_) => PreferredSize(
              child: SizedBox(
                  height: 40,
                  child: Center(
                    child: Text('Custom Footer'),
                  )),
              preferredSize: Size.fromHeight(40)),
        ),
        KeyboardActionsItem(focusNode: nodeText9, toolbarButtons: [
              (node) {
            return GestureDetector(
              onTap: () => node.unfocus(),
              child: Text(
                "完了",
                style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
              ),
            );
          },(node) {
            return SizedBox(width: 20,);
          }
        ])
      ],
    );
  }
}

**Comment by diegoveloper** [comment]
Add a minimum code to reproduce the issue and I'll check tomorrow , please format the code.

**Comment by SanthoseKumar118** [comment]
`import 'package:flutter/material.dart';
import 'customkeyboardactions.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController tecComment = TextEditingController();
  CustomKeyBoard keyBoardNode = CustomKeyBoard();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children:[
          Expanded(child: Container(height: double.infinity,)),
          sendMessage(),
        ],
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
  sendMessage() {
    return Container(height:64,decoration: BoxDecoration(color: Colors.white,border: Border(top: BorderSide(color: Colors.grey,width: 0.6))),
        child: Padding(padding: EdgeInsets.all(9),
            child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween,children: <Widget>[
              Expanded(child: search()),
              SizedBox(width: 10),
              TextButton(onPressed: (){}, child: Text('投稿する', style: TextStyle(fontSize: 14,fontWeight: FontWeight.bold),))
            ])));
  }

  search(){
    return KeyboardActions(
      config: keyBoardNode.buildConfig(context),
      child: Container(height: 44,
          child: TextField(
            focusNode: keyBoardNode.nodeText1,
      decoration: InputDecoration(prefixIconConstraints: BoxConstraints(maxWidth: 33),
          border: OutlineInputBorder(
              borderRadius: BorderRadius.all(Radius.circular(10)),
              borderSide: BorderSide(width: 1, color:Colors.grey.shade50)),
      hintText: "コメントする..."
      )
          )),
    );
  }
}

class CustomKeyBoard{
  final FocusNode nodeText1 = FocusNode();
  final FocusNode nodeText2 = FocusNode();
  final FocusNode nodeText3 = FocusNode();
  final FocusNode nodeText4 = FocusNode();
  final FocusNode nodeText5 = FocusNode();
  final FocusNode nodeText6 = FocusNode();
  final FocusNode nodeText7 = FocusNode();
  final FocusNode nodeText8 = FocusNode();
  final FocusNode nodeText9 = FocusNode();

  /// Creates the [KeyboardActionsConfig] to hook up the fields
  /// and their focus nodes to our [FormKeyboardActions].
  KeyboardActionsConfig buildConfig(BuildContext context) {
    return KeyboardActionsConfig(
      keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
      keyboardBarColor: Colors.grey[200],
      nextFocus: true,
      actions: [
        KeyboardActionsItem(enableArrows: false,
          focusNode: nodeText1,
          toolbarButtons: [
                (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Text(
                  "完了",
                  style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
                ),
              );
            }, (node) {
              return SizedBox(width: 20,);
            }
          ],),
        KeyboardActionsItem(focusNode: nodeText2, toolbarButtons: [
              (node) {
            return GestureDetector(
              onTap: () => node.unfocus(),
              child: Text(
                "完了",
                style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
              ),
            );
          },(node) {
            return SizedBox(width: 20,);
          }
        ]),
        KeyboardActionsItem(
          focusNode: nodeText3,
          toolbarButtons: [
                (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Text(
                  "完了",
                  style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
                ),
              );
            }, (node) {
              return SizedBox(width: 20,);
            }
          ],),
        KeyboardActionsItem(
          focusNode: nodeText4,
          toolbarButtons: [
                (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Text(
                  "完了",
                  style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
                ),
              );
            }, (node) {
              return SizedBox(width: 20,);
            }
          ],),
        KeyboardActionsItem(focusNode: nodeText5, toolbarButtons: [
              (node) {
            return GestureDetector(
              onTap: () => node.unfocus(),
              child: Text(
                "完了",
                style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
              ),
            );
          },(node) {
            return SizedBox(width: 20,);
          }
        ]),
        KeyboardActionsItem(
          focusNode: nodeText6,
          //displayCloseWidget: false,
        ),
        KeyboardActionsItem(
          focusNode: nodeText7,
          toolbarButtons: [
            //button 1
                (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Container(
                  color: Colors.white,
                  padding: EdgeInsets.all(8.0),
                  child: Text(
                    "CLOSE",
                    style: TextStyle(color: Colors.black),
                  ),
                ),
              );
            },
            //button 2
                (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Container(
                  color: Colors.black,
                  padding: EdgeInsets.all(8.0),
                  child: Text(
                    "DONE",
                    style: TextStyle(color: Colors.white),
                  ),
                ),
              );
            }
          ],
        ),
        KeyboardActionsItem(
          focusNode: nodeText8,
          footerBuilder: (_) => PreferredSize(
              child: SizedBox(
                  height: 40,
                  child: Center(
                    child: Text('Custom Footer'),
                  )),
              preferredSize: Size.fromHeight(40)),
        ),
        KeyboardActionsItem(focusNode: nodeText9, toolbarButtons: [
              (node) {
            return GestureDetector(
              onTap: () => node.unfocus(),
              child: Text(
                "完了",
                style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
              ),
            );
          },(node) {
            return SizedBox(width: 20,);
          }
        ])
      ],
    );
  }
}
`

**Comment by SanthoseKumar118** [comment]
'''
import 'package:flutter/material.dart';
import 'customkeyboardactions.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController tecComment = TextEditingController();
  CustomKeyBoard keyBoardNode = CustomKeyBoard();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children:[
          Expanded(child: Container(height: double.infinity,)),
          sendMessage(),
        ],
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
  sendMessage() {
    return Container(height:64,decoration: BoxDecoration(color: Colors.white,border: Border(top: BorderSide(color: Colors.grey,width: 0.6))),
        child: Padding(padding: EdgeInsets.all(9),
            child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween,children: <Widget>[
              Expanded(child: search()),
              SizedBox(width: 10),
              TextButton(onPressed: (){}, child: Text('投稿する', style: TextStyle(fontSize: 14,fontWeight: FontWeight.bold),))
            ])));
  }

  search(){
    return KeyboardActions(
      config: keyBoardNode.buildConfig(context),
      child: Container(height: 44,
          child: TextField(
            focusNode: keyBoardNode.nodeText1,
      decoration: InputDecoration(prefixIconConstraints: BoxConstraints(maxWidth: 33),
          border: OutlineInputBorder(
              borderRadius: BorderRadius.all(Radius.circular(10)),
              borderSide: BorderSide(width: 1, color:Colors.grey.shade50)),
      hintText: "コメントする..."
      )
          )),
    );
  }
}
'''

**Comment by SanthoseKumar118** [comment]
```
function test() {
  console.log("notice the blank line before this function?");
}
```

**Comment by SanthoseKumar118** [comment]
```
import 'package:flutter/material.dart';
import 'customkeyboardactions.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController tecComment = TextEditingController();
  CustomKeyBoard keyBoardNode = CustomKeyBoard();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children:[
          Expanded(child: Container(height: double.infinity,)),
          sendMessage(),
        ],
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
  sendMessage() {
    return Container(height:64,decoration: BoxDecoration(color: Colors.white,border: Border(top: BorderSide(color: Colors.grey,width: 0.6))),
        child: Padding(padding: EdgeInsets.all(9),
            child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween,children: <Widget>[
              Expanded(child: search()),
              SizedBox(width: 10),
              TextButton(onPressed: (){}, child: Text('投稿する', style: TextStyle(fontSize: 14,fontWeight: FontWeight.bold),))
            ])));
  }

  search(){
    return KeyboardActions(
      config: keyBoardNode.buildConfig(context),
      child: Container(height: 44,
          child: TextField(
            focusNode: keyBoardNode.nodeText1,
      decoration: InputDecoration(prefixIconConstraints: BoxConstraints(maxWidth: 33),
          border: OutlineInputBorder(
              borderRadius: BorderRadius.all(Radius.circular(10)),
              borderSide: BorderSide(width: 1, color:Colors.grey.shade50)),
      hintText: "コメントする..."
      )
          )),
    );
  }
}
```

**Comment by SanthoseKumar118** [comment]
@diegoveloper I have added the minimum code. Please check it with the images that I added before. Please let me how to resolve it. Thank you.

**Comment by diegoveloper** [comment]
I don't know what's `import 'customkeyboardactions.dart';` and `CustomKeyBoard` , that's not minimal code

**Comment by SanthoseKumar118** [comment]
I have took your code and added it in custom class. can you check this.

```
import 'package:flutter/material.dart';
import 'customkeyboardactions.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController tecComment = TextEditingController();
  CustomKeyBoard keyBoardNode = CustomKeyBoard();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        children:[
          Expanded(child: Container(height: double.infinity,)),
          sendMessage(),
        ],
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
  sendMessage() {
    return Container(height:64,decoration: BoxDecoration(color: Colors.white,border: Border(top: BorderSide(color: Colors.grey,width: 0.6))),
        child: Padding(padding: EdgeInsets.all(9),
            child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween,children: <Widget>[
              Expanded(child: search()),
              SizedBox(width: 10),
              TextButton(onPressed: (){}, child: Text('投稿する', style: TextStyle(fontSize: 14,fontWeight: FontWeight.bold),))
            ])));
  }

  search(){
    return KeyboardActions(
      config: keyBoardNode.buildConfig(context),
      child: Container(height: 44,
          child: TextField(
            focusNode: keyBoardNode.nodeText1,
      decoration: InputDecoration(prefixIconConstraints: BoxConstraints(maxWidth: 33),
          border: OutlineInputBorder(
              borderRadius: BorderRadius.all(Radius.circular(10)),
              borderSide: BorderSide(width: 1, color:Colors.grey.shade50)),
      hintText: "コメントする..."
      )
          )),
    );
  }
}

class CustomKeyBoard{
  final FocusNode nodeText1 = FocusNode();
  final FocusNode nodeText2 = FocusNode();
  final FocusNode nodeText3 = FocusNode();
  final FocusNode nodeText4 = FocusNode();
  final FocusNode nodeText5 = FocusNode();
  final FocusNode nodeText6 = FocusNode();
  final FocusNode nodeText7 = FocusNode();
  final FocusNode nodeText8 = FocusNode();
  final FocusNode nodeText9 = FocusNode();

  /// Creates the [KeyboardActionsConfig] to hook up the fields
  /// and their focus nodes to our [FormKeyboardActions].
  KeyboardActionsConfig buildConfig(BuildContext context) {
    return KeyboardActionsConfig(
      keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
      keyboardBarColor: Colors.grey[200],
      nextFocus: true,
      actions: [
        KeyboardActionsItem(enableArrows: false,
          focusNode: nodeText1,
          toolbarButtons: [
                (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Text(
                  "完了",
                  style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
                ),
              );
            }, (node) {
              return SizedBox(width: 20,);
            }
          ],),
        KeyboardActionsItem(focusNode: nodeText2, toolbarButtons: [
              (node) {
            return GestureDetector(
              onTap: () => node.unfocus(),
              child: Text(
                "完了",
                style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
              ),
            );
          },(node) {
            return SizedBox(width: 20,);
          }
        ]),
        KeyboardActionsItem(
          focusNode: nodeText3,
          toolbarButtons: [
                (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Text(
                  "完了",
                  style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
                ),
              );
            }, (node) {
              return SizedBox(width: 20,);
            }
          ],),
        KeyboardActionsItem(
          focusNode: nodeText4,
          toolbarButtons: [
                (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Text(
                  "完了",
                  style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
                ),
              );
            }, (node) {
              return SizedBox(width: 20,);
            }
          ],),
        KeyboardActionsItem(focusNode: nodeText5, toolbarButtons: [
              (node) {
            return GestureDetector(
              onTap: () => node.unfocus(),
              child: Text(
                "完了",
                style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
              ),
            );
          },(node) {
            return SizedBox(width: 20,);
          }
        ]),
        KeyboardActionsItem(
          focusNode: nodeText6,
          //displayCloseWidget: false,
        ),
        KeyboardActionsItem(
          focusNode: nodeText7,
          toolbarButtons: [
            //button 1
                (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Container(
                  color: Colors.white,
                  padding: EdgeInsets.all(8.0),
                  child: Text(
                    "CLOSE",
                    style: TextStyle(color: Colors.black),
                  ),
                ),
              );
            },
            //button 2
                (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Container(
                  color: Colors.black,
                  padding: EdgeInsets.all(8.0),
                  child: Text(
                    "DONE",
                    style: TextStyle(color: Colors.white),
                  ),
                ),
              );
            }
          ],
        ),
        KeyboardActionsItem(
          focusNode: nodeText8,
          footerBuilder: (_) => PreferredSize(
              child: SizedBox(
                  height: 40,
                  child: Center(
                    child: Text('Custom Footer'),
                  )),
              preferredSize: Size.fromHeight(40)),
        ),
        KeyboardActionsItem(focusNode: nodeText9, toolbarButtons: [
              (node) {
            return GestureDetector(
              onTap: () => node.unfocus(),
              child: Text(
                "完了",
                style: TextStyle(color: Color(0xFF007AFF),fontWeight: FontWeight.w700),
              ),
            );
          },(node) {
            return SizedBox(width: 20,);
          }
        ])
      ],
    );
  }
}
```

**Comment by diegoveloper** [comment]
I wouldn't use this package on your case, remove 

```KeyboardActions(
      config: keyBoardNode.buildConfig(context),
   ```   
 Just add the arrow items below your `sendMessage() `widget,
 
      
 and it will work fine,

**Comment by SanthoseKumar118** [comment]
Can We have meeting on Google Meet So that I we can Explain you clearly. 
I will share the Google meet link if you are available.

**Comment by SanthoseKumar118** [comment]
That is not arrow Item That is a keyboard action Bar. That is the output of this plugin. How can I add that below sendMessage() widget.
