### ISSUE TITLE
Gap between top of the action bar and page content

### ISSUE THREAD

**Issue by BenjaminFarquhar** [diegoveloper/flutter_keyboard_actions#172]
flutter_keyboard_actions is adding a gap between the keyboard action bar and my page content. How can I make my page content go all the way down to the keyboard action bar?

![IMG_1954](https://user-images.githubusercontent.com/26356162/147390770-510020a9-5339-4bd4-84c9-b329f9c29844.PNG)
![IMG_1955](https://user-images.githubusercontent.com/26356162/147390774-0401f0c2-bbc5-4ac7-b096-b0d6e37b13a7.PNG)

**Comment by diegoveloper** [comment]
Try to reproduce the issue on a minimum sample code, then paste the code here.

**Comment by BenjaminFarquhar** [comment]
Not sure if this code is minimal enough. I think it is my code that is causing it actually. Maybe the Expanded is stretching it out:

```
    return [
      Expanded(
          child: KeyboardActions(
              tapOutsideBehavior: TapOutsideBehavior.opaqueDismiss,
              config: KeyboardActionsConfig(
                defaultDoneWidget: const VpKeyboardDoneButton(),
                actions: [
                  KeyboardActionsItem(
                    focusNode: focusNodeName,
                  ),
                  KeyboardActionsItem(
                    focusNode: focusNodeLocationName,
                  ),
                  KeyboardActionsItem(
                    focusNode: focusNodeCompanyName,
                  ),
                  KeyboardActionsItem(
                    focusNode: focusNodeDescription,
                  ),
                ],
              ),
              child: Column(mainAxisSize: MainAxisSize.min, children: [
                nameTextField(context: context!, form: form),
                locationNameTextField(context: context, form: form!),
                companyNameTextField(context: context, form: form),
                descriptionTextField(context: context, vm: vm),
              ])))
    ];
```

**Comment by diegoveloper** [comment]
No, that's not minimal, try creating a new file from empty project,
something that I could run here and reproduce the issue.

**Comment by BenjaminFarquhar** [comment]
I am having trouble with that. But if this helps, it doesn't have the gap when I do `disableScroll: true`. It is the area that scrolls which becomes empty.

**Comment by BenjaminFarquhar** [comment]
I'm pretty sure it is this: https://github.com/diegoveloper/flutter_keyboard_actions/issues/48 It seems like a bug with autoscroll.

**Comment by BenjaminFarquhar** [comment]
If I have anything that takes up space below my `KeyboardActions()` then it increases that gap. If I remove everything below it then it is fixed. But I need to have a button below it.

**Comment by BenjaminFarquhar** [comment]
It is a bug.

When you calculate the offset to "avoid" EG:

```
BottomAreaAvoider(
                key: bottomAreaAvoiderKey,
                areaToAvoid: _offset
```
                
It calculates the action bar height (45) + the device keyboard height:

```
    double newOffset = _currentAction!.displayActionBar
        ? _kBarSize
        : 0; // offset for the actions bar
    newOffset += MediaQuery.of(context)
        .viewInsets
        .bottom; // + offset for the system keyboard
```

The `KeyboardActions` widget then applies this offset, starting from the bottom of the `KeyboardActions` widget, which means if the `KeyboardActions` widget isn't at the bottom of the page, the offset will be too high - by the height of whatever is below it. It needs to at the very least have an offset parameter to pass to the `KeyboardActions` which is the distance from the bottom of the screen to the bottom of the `KeyboardActions`.

**Comment by diegoveloper** [comment]
Would you mind creating a PR to fix this issue? :D

**Comment by BenjaminFarquhar** [comment]
@diegoveloper  Sure, I will give it a go

**Comment by BenjaminFarquhar** [comment]
@diegoveloper I have tried to push to my new branch "benjamin-farquhar/bug/172-fix-offset"; however, access is denied. Do you need to permit me?

**Comment by diegoveloper** [comment]
You need to fork the project then send a PR
