### ISSUE TITLE
bug: Impossible to switch between default keyboard and custom keyboard

### ISSUE THREAD

**Issue by Arenukvern** [diegoveloper/flutter_keyboard_actions#173]
First of all, thank you for the awesome package!

Found out, if you have one input with a default keyboard and a second focus with a custom keyboard, it is not possible to open the custom keyboard if the default keyboard is open.

This issue is reproducible within the example folder with Keyboard Actions Sample
![Screen Recording 2021-12-26 at 5 36 49 am](https://user-images.githubusercontent.com/15068151/147395580-3bb27f41-8fa7-45f5-a019-5b27ee1b6093.gif)

To reproduce this behaviour you first click Input Number and then click for any custom keyboard.

As a workaround in my project, I've used the listener and delayed future
```dart
return Focus(
  focusNode: emojisFocusNode,
  child: GestureDetector(
    onTap: () {
      final keyboardOpen = window.viewInsets.bottom > 0;
      if (keyboardOpen) {
        focusNode.unfocus();
        Future.delayed(const Duration(milliseconds: 200),  otherFocusNode.requestFocus);
      } else {
        otherFocusNode.requestFocus();
      }
    },
    child: const Icon(Icons.emoji_flags_rounded),
  ),
);
```

**Comment by diegoveloper** [comment]
Don't forget PR are open

**Comment by Arenukvern** [comment]
> Don't forget PR are open
> […](#)

thank you!
found a reason, will do PR
