### ISSUE TITLE
Give example on how to write tests

### ISSUE THREAD

**Issue by ValentinVignal** [diegoveloper/flutter_keyboard_actions#179]
Hello, I'm using your package and I'm trying to write tests.
My first idea was to copy what you've done, but I don't see any. 

Is it possible for you to write some tests so we can copy them?

**Comment by diegoveloper** [comment]
We don't have test for this package, I recommend you to start looking for info about writing widget test on Flutter.

**Comment by ValentinVignal** [comment]
Hello @diegoveloper. May I know why there is no test for this package ? 

Thanks for the feedback, but I have an issue mocking the `Platform` in my tests. How can I write a test for `Platform.iOS` or `Platform.android` etc ?

**Comment by diegoveloper** [comment]
Yeah, I didn't add tests because I don't have enough free time. Don't forget you can ask technical questions on stackoverflow.
