### ISSUE TITLE
 Done button not working with a multiline textformfield

### ISSUE THREAD

**Issue by chrisvidal** [diegoveloper/flutter_keyboard_actions#184]
the Done button is not working when we use a multiline textformfield:

```dart
TextFormField(
  controller: descriptionController,
  focusNode: _nodeText1,
  keyboardType: TextInputType.multiline,
  textInputAction: TextInputAction.newline,
  minLines: 1,
  maxLines: 10,
},
```

with 

```dart
KeyboardActions(      
      config: _buildKeyboardConfig(context),
      child: SingleChildScrollView(
```

```dart
final FocusNode _nodeText1 = FocusNode();
    KeyboardActionsConfig _buildKeyboardConfig(BuildContext context) {
      return KeyboardActionsConfig(
        keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
        keyboardBarColor: Colors.grey[200],
        nextFocus: false,
        actions: [
          KeyboardActionsItem(
            focusNode: _nodeText1,
          ),
        ],
      );
    }
```

**Comment by diegoveloper** [comment]
I modified the current example `content.dart` and it worked

![simulator_screenshot_D4E79D07-8F9B-455E-BE88-8D3C0A541001](https://user-images.githubusercontent.com/4898256/154083375-be5ab48c-37b5-437f-b0f3-4e3f25b9f913.png)

**Comment by chrisvidal** [comment]
it displays the `done` but the tap on `done` button is not working

**Comment by diegoveloper** [comment]
I tried and it worked. (Using the current example from the repo).

Maybe you could add a minimum code to reproduce the issue.

**Comment by chrisvidal** [comment]
ok found the root of the issue.
the bug is coming from the presence of a controller or not in the TextFormField.
It works without a controller, and it does not work if there is a controller like in my example.

**Comment by chrisvidal** [comment]
when this a controller specified the behaviour is as follows:
you type text in the field
you tap `Done` nothing is happening
you tap/get focus back in the field
you tap `Done` again and it works.

it should be working at the first Tap on `Done`.

**Comment by diegoveloper** [comment]
Please add a minimum code in order to reopen the issue. (A video if it's possible)

**Comment by chrisvidal** [comment]
all my code is up there in the first post. Doi you need something else?

**Comment by chrisvidal** [comment]
the controller implements a listener

in the view:
```dart
final TextEditingController descriptionController = TextEditingController();

// initState
listenToFormUpdated(model);

```

in my viewmodel:

```dart
  void listenToFormUpdated(FormViewModel model) {
    descriptionController.addListener(() => _updateFormData(model));
  }

/// Updates the formData on the FormViewModel
  void _updateFormData(FormViewModel model) => model.setData(
        model.formValueMap
          ..addAll({
            DescriptionValueKey: descriptionController.text,
          }),
      );

```

I noticed that if I switch the listener, then the `Done` is acting properly.
with the controller listener, the field is losing focus somehow.

**Comment by chrisvidal** [comment]
I think I solved the issue without really understanding what is happening.

My ViewModel is creating another FocusNode which apparently disturbed the KeyboardAction `done` button to work properly if I am not using this one but a new one.
