### ISSUE TITLE
weird behavior when using autofocus:true on iOS

### ISSUE THREAD

**Issue by MarcVanDaele90** [diegoveloper/flutter_keyboard_actions#186]
When using the following code

```
class TestLayout extends StatefulWidget {
  TestLayout({Key? key}) : super(key: key);

  @override
  State<TestLayout> createState() => _TestLayoutState();
}

class _TestLayoutState extends State<TestLayout> {
  FocusNode focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return KeyboardActions(
      config:
          KeyboardActionsConfig(keyboardActionsPlatform: KeyboardActionsPlatform.ALL, keyboardBarColor: Colors.grey[200], nextFocus: false, actions: [
        KeyboardActionsItem(focusNode: focusNode)
      ]),
      child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
        TextFormField(
          focusNode: focusNode,
          autofocus: true,
        ),
      ]));
  }
}
```

I get a focused TextFormField and the "Done" button at the bottom.  When I select the TextFormField, the keyboard pops up and then the "Done" button is not at the top of the keyboard but much higher (see screenshot).  The button isn't functional either.   When I remove the autofocus, things works as expected.

![image](https://user-images.githubusercontent.com/90178346/161947602-4532fe69-5567-4f37-b8ad-5c3f80bfd0b8.png)

**Comment by diegoveloper** [comment]
I can't reproduce the issue on Android, neither iOS.

![Screen Shot 2022-04-06 at 9 17 18 AM](https://user-images.githubusercontent.com/4898256/161995857-e7651076-4bd6-4e6a-9051-d2e35e7b423c.png)


Which version of the package are you using?
Which flutter version are you using? (paste flutter doctor here).

**Comment by MarcVanDaele90** [comment]
Hello, 
I'm using `  keyboard_actions: ^3.4.7` and the output of `flutter doctor -v` is added below.  I have an iPhone XR running IOS 15.1. 

Note that I have an additional line on my keyboard-screenshot, above the the yep / ok / I line that contains icons for password/creditcard and locations together with a non-functional "Done" button.  
I have no clue why I see them, nor how I can get rid of them.  I see them only in Flutter textfields, not in other textfields of other iOS applications.   Maybe this is somehow related to the problem I'm facing?  If you have suggestions on how to remove this line I can test again on my side and see whether this fixes the issue.

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.3, on Linux Mint 20.2 5.11.0-43-generic,
    locale en_US.UTF-8)
    • Flutter version 2.10.3 at /home/marc/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (5 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/marc/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/marc/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/marc/android-studio
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.65.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 20.2 5.11.0-43-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by aveit** [comment]
@MarcVanDaele90 did you manage to solve your issue? I'm facing the same behavior.

**Comment by MarcVanDaele90** [comment]
@aveit unfortunately not

**Comment by aveit** [comment]
Hey @MarcVanDaele90 and @diegoveloper I've just found the issue on my code and it wasn't related to the `flutter_keyboard_actions` package, it was the property `resizeToAvoidBottomInset: false` in the first `Scaffold` of my widget tree that apparently was causing this issue. Once I removed it, everything looks fine then.
