### ISSUE TITLE
Flutter Web: Prev/Next/Done button from the keyboard appears under the custom prev/next/done button from this package

### ISSUE THREAD

**Issue by nerakatiryrref** [diegoveloper/flutter_keyboard_actions#187]
Hi,

I tried on flutter web on ios browser (chrome or safari), the prev/next/done button from the keyboard appears under the prev/next/done button from flutter_keyboard_actions.

**Comment by diegoveloper** [comment]
Add screenshots

**Comment by diegoveloper** [comment]
@nerakatiryrref can you add more information? screenshots would help.

**Comment by nerakatiryrref** [comment]
![IMG_8419](https://user-images.githubusercontent.com/98793217/162555136-d90e37b0-9289-4654-8ad5-cd2da30abea7.PNG)

Hi,attached the screenshot.

**Comment by nerakatiryrref** [comment]
I am running the example app using chrome / safari browser in iOS. Android browser works as expected (only one toolbar from keyboard action package)

**Comment by diegoveloper** [comment]
hmmm those actions are part of the keyboard I think, so is out of the control of `keyboard_actions`, maybe you have some options in your device keyboard settings.

**Comment by nerakatiryrref** [comment]
Hi,

Thanks for your reply. This issue not only appears in my device, but in several iOS device. The keyboard setting is default. No special / custom setting. You may have to check it by your self using iOS simulator.

**Comment by Justus-M** [comment]
I wonder if this should be higher than P4?

Every user running a new flutter web app in chrome will face an unresponsive 'done' button. I've been trying all day to find a workaround but this button can't be removed and textfield doesn't detect when this button is pressed.

**Comment by diegoveloper** [comment]
are you using the google keyboard? https://apps.apple.com/pe/app/gboard-the-google-keyboard/id1091700242?l=en

**Comment by Justus-M** [comment]
> https://apps.apple.com/pe/app/gboard-the-google-keyboard/id1091700242?l=en

This happens with the default chrome keyboard on iOS.

Have you tried it out?

**Comment by Justus-M** [comment]
![simulator_screenshot_87879490-39FA-47F8-80C6-7023FC2AA5D9](https://user-images.githubusercontent.com/37046316/186954064-81088e0d-f68b-4111-9fd2-241daa81e7bd.png)
*Fertig means done in german

**Comment by diegoveloper** [comment]
![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-08-26 at 11 51 16](https://user-images.githubusercontent.com/4898256/186954232-2e1a2e98-cc8d-408a-bcb1-a371a13fa92b.png)
![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-08-26 at 11 51 19](https://user-images.githubusercontent.com/4898256/186954239-27b4842c-9620-4635-8b80-3583dfb1cdb6.png)

Which iOS version are you using?

**Comment by Justus-M** [comment]
> ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-08-26 at 11 51 16](https://user-images.githubusercontent.com/4898256/186954232-2e1a2e98-cc8d-408a-bcb1-a371a13fa92b.png) ![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-08-26 at 11 51 19](https://user-images.githubusercontent.com/4898256/186954239-27b4842c-9620-4635-8b80-3583dfb1cdb6.png)
> 
> Which iOS version are you using?

You are in the app.

This issue we are reporting is in the browser

**Comment by diegoveloper** [comment]
ah sorry, do you need keyboard actions in browser? maybe you can check https://api.flutter.dev/flutter/foundation/kIsWeb-constant.html and avoid keyboard actions when the release is for web.

**Comment by Justus-M** [comment]
@diegoveloper Thanks for trying to help. Unfortunately the keyboard actions (in the bar above the keyboard) can't be turned off with textfield/textformfield in flutter web.

**Comment by Justus-M** [comment]
I think this can't be changed
https://github.com/flutter/flutter/issues/92024#issuecomment-947479222

**Comment by diegoveloper** [comment]
```
 KeyboardActions(
    enabled: !kisWeb,
```
(https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/lib/keyboard_actions.dart#L65)

**Comment by Justus-M** [comment]
Ah sorry I thought you meant disable the default bar, not the custom KeyboardActions.

OP wanted to use custom keyboard actions instead of the default, so did I, so this is not a solution.

I think this cannot be achieved as explained in the comment I linked in my previous comment
