### ISSUE TITLE
Keyboard actions shown without keyboard if using bluetooth keyboard.

### ISSUE THREAD

**Issue by lawkeen** [diegoveloper/flutter_keyboard_actions#188]
Hi, if you are using iOS simulator keyboard with only hardware keyboard or if you are connected bluetooth keyboard to your prone, then keyboard will not appear, but the actions will be. How to disable actions if hardware keyboard using? 

![Simulator Screen Shot - iPhone 13 - 2022-04-15 at 02 12 09](https://user-images.githubusercontent.com/46008086/163492258-fc5ffba2-7fda-4527-96c6-7a59e19177d0.png)

**Comment by diegoveloper** [comment]
I didn't try but maybe you could use `RawKeyboardListener` https://api.flutter.dev/flutter/widgets/RawKeyboardListener-class.html , and use a `focusNode` var, listen the node and when it has the focus, maybe you can change the property of this :  https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/lib/keyboard_actions.dart#L65  to false

**Comment by lawkeen** [comment]
Yep, already tried, working buggy. If switch keyboard then focused, KeyboardActions.enbaled not changing state only if unfocus and rebuild whole screen state. Green container - keyboard visible, red - not visible. Don't know how to handle :(
                         
[Simulator Screen Recording - iPhone 13 - 2022-04-15 at 03.06.26.gif.zip](https://github.com/diegoveloper/flutter_keyboard_actions/files/8492963/Simulator.Screen.Recording.-.iPhone.13.-.2022-04-15.at.03.06.26.gif.zip)

**Comment by diegoveloper** [comment]
I don't know a way to detect if the hardware keyboard is connected. Would you mind to create this question in stackoverflow? maybe someone can help there.

**Comment by lawkeen** [comment]
I know the way, but still have problems with rebuilding KeyboardActions. Thank you for answers anyway.

**Comment by diegoveloper** [comment]
> I know the way, but still have problems with rebuilding KeyboardActions. Thank you for answers anyway.

PRs are welcome :)

**Comment by lawkeen** [comment]
Yeah, will try to handle this and send it to you in PR later :)
