### ISSUE TITLE
improvement: pass default config as a parameter to FormKeyboardActions

### ISSUE THREAD

**Issue by jaysephjw** [diegoveloper/flutter_keyboard_actions#20]
This is the way the API worked before adding `FormKeyboardActions.setKeyboardActions`. It would be nice to pass an initial configuration in during widget construction for easier usage.

**Comment by diegoveloper** [comment]
Hi @jaysephjw I did some changes to have the old API for easier usage : https://github.com/diegoveloper/flutter_keyboard_actions/tree/dev   what do you think?

**Comment by jaysephjw** [comment]
LGTM, left one tiny comment.

**Comment by diegoveloper** [comment]
Thanks for the feedback, it still has some bugs , do you have some time to help me with these?
- Sometimes it pushes the textfield with an incorrect offset.
- On dialog it works weird.
- Some animation issues using custom keyboard (it can be reproduced on the Full screen form example), going top/down with the arrows.

**Comment by jaysephjw** [comment]
I don't currently have time to look, sorry!

I wonder if the custom keyboard should be its own project, or at least
labeled "experimental",  since it definitely makes the functionality more
complicated and is harder to get right.
