### ISSUE TITLE
'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.

### ISSUE THREAD

**Issue by Fantome5** [diegoveloper/flutter_keyboard_actions#204]
../../../../../../flutter/.pub-cache/hosted/pub.dartlang.org/keyboard_actions-4.0.0/lib/keyboard_actions.dart:283:33: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
     - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    Try calling using ?. instead.
            WidgetsBinding.instance.addPostFrameCallback((_) {

**Comment by Fantome5** [comment]
How do I fix this? Upgrade?

**Comment by diegoveloper** [comment]
Yes, upgrade Flutter. Also, that's not an error, it's just a warning.
