### ISSUE TITLE
If keyboard actions is used on a single textfield, keyboardactions bar overlaps the textfield

### ISSUE THREAD

**Issue by joeldegerman99** [diegoveloper/flutter_keyboard_actions#206]
If a single textfield is used in a list, when it get's focused and scrolled into view (if the keyboard was hiding it) the keyboardactions bar overlaps half of the textfield

**Comment by joeldegerman99** [comment]
![image](https://user-images.githubusercontent.com/79711461/189127556-b7b17852-f054-4ad8-96c1-581135b043cb.png)

**Comment by diegoveloper** [comment]
Code?

**Comment by joeldegerman99** [comment]
```
import 'package:flutter/material.dart';
import 'package:keyboard_actions/keyboard_actions.dart';

class TestPage extends StatelessWidget {
  TestPage({super.key});

  FocusNode node = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          children: [
            Container(
              height: 100,
              margin: const EdgeInsets.all(15),
              width: double.infinity,
              color: Colors.red,
            ),
            Container(
              height: 100,
              margin: const EdgeInsets.all(15),
              width: double.infinity,
              color: Colors.red,
            ),
            Container(
              height: 100,
              margin: const EdgeInsets.all(15),
              width: double.infinity,
              color: Colors.red,
            ),
            Container(
              height: 100,
              margin: const EdgeInsets.all(15),
              width: double.infinity,
              color: Colors.red,
            ),
            Container(
              height: 100,
              margin: const EdgeInsets.all(15),
              width: double.infinity,
              color: Colors.red,
            ),
            KeyboardActions(
              disableScroll: true,
              config: KeyboardActionsConfig(
                  actions: [KeyboardActionsItem(focusNode: node)]),
              child: TextField(
                focusNode: node,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

Press the textfield, scroll up and then type something to make it scroll into view

**Comment by joeldegerman99** [comment]
This code is to emulate a page with multiple items and a single textfield

**Comment by joeldegerman99** [comment]
I understand that this is not really an issue with this package, since you are using an overlay entry to place the action bar flutter does not know that the viewInsets is now the soft keyboard size plus the action bar size

**Comment by diegoveloper** [comment]
Did you try moving `KeyboardActions` at the top of your `Column` ?

**Comment by sakaev2901** [comment]
@joeldegerman99, problem is solving simply by passing parameter **scrollPadding** on **TextField** widget

**Comment by joeldegerman99** [comment]
@sakaev2901 @diegoveloper This is what I was searching for! Thanks!
 @diegoveloper you should update the docs with some information that you should change the scrollPadding if you are using the keyboardaction on a single non scrollable textfield

**Comment by altoon-dev** [comment]
> @sakaev2901 @diegoveloper This is what I was searching for! Thanks! @diegoveloper you should update the docs with some information that you should change the scrollPadding if you are using the keyboardaction on a single non scrollable textfield

how did u solve exactly?

**Comment by joeldegerman99** [comment]
> > @sakaev2901 @diegoveloper This is what I was searching for! Thanks! @diegoveloper you should update the docs with some information that you should change the scrollPadding if you are using the keyboardaction on a single non scrollable textfield
> 
> how did u solve exactly?

You just add a scrollPadding to a TextField and give it an `EdgeInsets` value and then it will pad the textfield the amount you added.

If you add 
``` 
TextField(
  scrollPadding: EdgeInsets.only(bottom: 40),
);
```
it will make the so that the textfield on focus is pushed up double the amount of the default value of 
`20`

The default is `EdgeInsets.all(20)` but i used the bottom and it worked as expected
