### ISSUE TITLE
Tried to get the bounds of a focus node that didn't have its context set yet

### ISSUE THREAD

**Issue by BenjiFarquhar** [diegoveloper/flutter_keyboard_actions#212]
I'm getting this exception when I try to unfocus a text field by physically tapping elsewhere on the screen. It causes the application to become unresponsive because the text field remains focused. Not really sure why this is happening but  `package:keyboard_actions/keyboard_actions` is in the stack.

════════ Exception caught by gesture library ═══════════════════════════════════
The following assertion was thrown while dispatching a pointer event:
Tried to get the bounds of a focus node that didn't have its context set yet.
The context needs to be set before trying to evaluate traversal policies. Setting the context is typically done with the attach method.
'package:flutter/src/widgets/focus_manager.dart':
package:flutter/…/widgets/focus_manager.dart:1
Failed assertion: line 790 pos 7: 'context != null'

When the exception was thrown, this was the stack
#2      FocusNode.rect
package:flutter/…/widgets/focus_manager.dart:790
#3      KeyboardActionstate._insertOverlay.<anonymous closure>.<anonymous closure>
package:keyboard_actions/keyboard_actions.dart:341
#4      RenderPointerListener.handleEvent
package:flutter/…/rendering/proxy_box.dart:3156
#5      GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:440
#6      RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:337
#7      GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:395
#8      GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:357
#9      GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:314
#10     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:295
#11     _invoke1 (dart:ui/hooks.dart:167:13)

Using this version:

    keyboard_actions: ^4.1.0
    keyboard_avoider: ^0.1.2

**Comment by BenjiFarquhar** [comment]
@diegoveloper I had actually removed the focus nodes from my TextFields because there was a bug that made it impossible to unfocus the TextField, and when I removed the focus node, the bug was resolved, but it means flutter_keyboard_actions no longer works. Do you have any ideas why TextFields could not unfocus fields when they were using focusNodes passed in to flutter_keyboard_actions?

**Comment by BenjiFarquhar** [comment]
Error is 

════════ Exception caught by gesture library ═══════════════════════════════════
Tried to get the bounds of a focus node that didn't have its context set yet.
The context needs to be set before trying to evaluate traversal policies. Setting the context is typically done with the attach method.
'package:flutter/src/widgets/focus_manager.dart':
package:flutter/…/widgets/focus_manager.dart:1
Failed assertion: line 790 pos 7: 'context != null'

**Comment by BenjiFarquhar** [comment]
This was an issue in my code. This appears to be caused by FocusNodes being shared by multiple inheriting classes. The fix was to make each inheriting class pass their own FocusNode into the super constructor.

**Comment by diegoveloper** [comment]
Not sure what's the error because there is no code

**Comment by BenjiFarquhar** [comment]
@diegoveloper Sorry, the code is quite abstract. The situation is where I have the text field in a super class and the inherited classes all pass in their own focus node. I thought the issue was the focus node is getting shared. But making them not shared does not resolve it. But if I make the focus nodes global, it fixes the issue. It must be resolved by the focus nodes now do not get disposed and recreated every time the widget is constructed.

**Comment by diegoveloper** [comment]
Try recreate the issue in a simple example, otherwise, we can't fix it.

**Comment by BenjiFarquhar** [comment]
@diegoveloper It is an issue with my code, apologies. It is a reconstruction issue. I have a form factory class with focus nodes in it, and when the form factory class is rebuilt (because it listens to Riverpod events, it is constructed in a Riverpod provider), the focus nodes are rebuilt, so the text fields now have different focus nodes, which destroys focusing and unfocusing. Confirmed by making the focus nodes global so they are not rebuilt. I will have to find a nicer way to fix at some point
