### ISSUE TITLE
Custom Keyboard Focus Issue

### ISSUE THREAD

**Issue by Ogre-Knight** [diegoveloper/flutter_keyboard_actions#214]
Hi there!
I am trying to develop an app with a Custom Keyboard.
But there is a little problem.
Create a container that receives input using a custom keyboard and a general text field.
And when you click Container after giving focus to the Text Field, the keyboard comes up, then loses the focus automatically and the keyboard goes down again.
How to solve this problem?

https://user-images.githubusercontent.com/108185245/213392460-3c043ee9-a0d4-48f7-a8cb-f4eef10be799.mp4

**Comment by diegoveloper** [comment]
I think this could be a stackoverflow question, try there

**Comment by raphire08** [comment]
Hi @Ogre-Knight 

Were you able to find the issue for this. We are also facing this ? It happens for android and not for iOS.
