### ISSUE TITLE
new version i can't run

### ISSUE THREAD

**Issue by absc** [diegoveloper/flutter_keyboard_actions#219]
this is my issues

`../../../../.pub-cache/hosted/pub.dartlang.org/keyboard_actions-4.2.0/lib/keyboard_actions.dart:322:31: Error: A value of type 'OverlayState?' can't be assigned to a variable of type 'OverlayState' because 'OverlayState?' is nullable and 'OverlayState' isn't.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('../../../workFile/%E5%BC%80%E5%8F%91sdk/flutterSdk/flutter/packages/flutter/lib/src/widgets/overlay.dart').
    OverlayState os = Overlay.of(context);`

**Comment by diegoveloper** [comment]
Don't use the newest version if you are not using flutter 3.7.x
