### ISSUE TITLE
Error when using version 4.2.0

### ISSUE THREAD

**Issue by DanielEidlin** [diegoveloper/flutter_keyboard_actions#220]
I get the following error when using version 4.2.0:

```
Error: Method 'getOffsetToReveal' cannot be called on 'RenderAbstractViewport?' because it is potentially null.
     - 'RenderAbstractViewport' is from 'package:flutter/src/rendering/viewport.dart'
     ('../../development/flutter/packages/flutter/lib/src/rendering/viewport.dart').
    Try calling using ?. instead.
      final offset = viewport.getOffsetToReveal(object, 1.0).offset + overscroll;
```

Looking at the code changes between the previous version and the current one, I think it has something to do with this change in `lib/external/keyboard_avoider/bottom_area_avoider.dart`:
```
+ final viewport = RenderAbstractViewport.of(object)!;
- final viewport = RenderAbstractViewport.of(object);
```

**Comment by diegoveloper** [comment]
What flutter version are you using? If you are not using the latest, you can use a lower version of this library

**Comment by DanielEidlin** [comment]
I'm using flutter 3.3.1. That's actually what I did, I'm using keyboard_actions 4.1.0 and it works fine.
Thanks for clarifying but maybe you can specify the minimal flutter version required somewhere, to avoid confusion.
