### ISSUE TITLE
Not working with flutter 3.10 on iOS

### ISSUE THREAD

**Issue by ChrisElliotUK** [diegoveloper/flutter_keyboard_actions#225]
The keyboard bar does not show on Flutter 3.10.

Steps to reproduce:
upgrade to 3.10
follow tutorial and

**Comment by ChrisElliotUK** [comment]
Actually I think this may be a flutter issue. If you run `print(MediaQuery.of(context).viewInsets.bottom);` when the keyboard is open it shows zero. Can anyone confirm?

**Comment by archi7** [comment]
facing the same issue right now on Flutter 3.10

**Comment by ChrisElliotUK** [comment]
If you are using screen_utils set `useInheritedMediaQuery: true`

[See here](https://github.com/OpenFlutter/flutter_screenutil/issues/477)

**Comment by asaarnak** [comment]
@ChrisElliotUK 
On 3.10
It scrolls the keyboard height correctly using `useInheritedMediaQuery: true`
The action bar height is not scrolled during first click(init).
The TextField is half-hidden.
During second click, not init, if you click on some other TextField and then click back on the TextField with Keyboard action bar then the action bar height is also scrolled and TextField is not half-hidden under action bar.
