### ISSUE TITLE
How to use with TextField full screen?

### ISSUE THREAD

**Issue by TabooSun** [diegoveloper/flutter_keyboard_actions#28]
Currently, I am using TextField with below configuration:

![image](https://user-images.githubusercontent.com/31196825/59961204-4c5d3f80-9507-11e9-804d-fb4b2f553ae7.png)

With this, the TextField will be expanded full screen, but I got the error below:

![image](https://user-images.githubusercontent.com/31196825/59961207-5aab5b80-9507-11e9-8c09-40223f298e08.png)

**Comment by diegoveloper** [comment]
Add a mininum sample code to reproduce the issue.

**Comment by TabooSun** [comment]
I follow the example code provided. 
The file below shows the code which causes this issue.

[TemplateAddingView.txt](https://github.com/diegoveloper/flutter_keyboard_actions/files/3317441/TemplateAddingView.txt)

**Comment by diegoveloper** [comment]
Try creating a little sample without using packages (only keyboard_actions), to run and reproduce the issue. You can add the code here: https://gist.github.com/

**Comment by TabooSun** [comment]
https://gist.github.com/TabooSun/90e5b3e280d99d79102d12af9662d224

I created a new project and tested it. Unfortunately, still not working.

**Comment by diegoveloper** [comment]
You just need to add a parent constraint to your `TextField`, something like this :

```
return SizedBox(
      height: 100,
      child: TextField(
        focusNode: _templateTextNode,
        expands: true,
        maxLines: null,
        keyboardType: TextInputType.multiline,
        decoration: InputDecoration(
          contentPadding: EdgeInsets.all(16.0),
          labelText: "Input here",
          hintText: "Hint",
          hintStyle: TextStyle(color: Colors.blue),
          alignLabelWithHint: true,
          border: UnderlineInputBorder(
            borderSide: BorderSide.none,
          ),
        ),
      ),
    );
```

If you want full height try using `MediaQuery.of(context).size.height` instead of 100

**Comment by TabooSun** [comment]
It works, thanks.
