### ISSUE TITLE
Can't it be used in the showModalBottomSheet？？

### ISSUE THREAD

**Issue by abings** [diegoveloper/flutter_keyboard_actions#30]
Can't it be used in the showModalBottomSheet？？Please help.

**Comment by diegoveloper** [comment]
Could you add code to reproduce the issue?

**Comment by zyzhangyu** [comment]
I have encountered the same problem。
In the beginning, I thought this might be a bug in the library!
Later I checked my code and found that it might be a problem with my build method!

#This OK
``` 
    return Scaffold(
        body: Builder(builder: (context) {
      return Container(
```

#This error
``` 
    return Scaffold(
        body: Container
```

@abings
