### ISSUE TITLE
FocusNode dispose generate error

### ISSUE THREAD

**Issue by jnickzlim** [diegoveloper/flutter_keyboard_actions#31]
**App Structure:**
```
Home
| -> Register Page
| -> Login Page
```

**Replicate the Error:**
To replicate this error, you will need to create a home page and the home screen will link to register screen and setup the FormKeyboardActions just like the example, when clicking back button from the Register Screen to navigate back to Home Screen, the following error occur.

**Code that cause the error:**
```
void dispose() {
    _nodeText1.dispose();
    _nodeText2.dispose();
    _nodeText3.dispose();
    _nodeText4.dispose();
    super.dispose();
}
```

**Error:**
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while finalizing the widget tree:
flutter: A FocusNode was used after being disposed.
flutter: Once you have called dispose() on a FocusNode, it can no longer be used.
```

Note: From what i understand, we should be disposing the FocusNode at dispose(), and this cause the error to show up, please correct me if i am wrong.

**Comment by diegoveloper** [comment]
You don't need to dispose the focusNode

**Comment by jnickzlim** [comment]
Noted, thank you for the info
