### ISSUE TITLE
Dark Mode - Background and Buttons color in white

### ISSUE THREAD

**Issue by jnickzlim** [diegoveloper/flutter_keyboard_actions#32]
<img width="379" alt="Screenshot 2019-07-25 at 9 35 33 AM" src="https://user-images.githubusercontent.com/35293490/61839318-b75fb480-aebf-11e9-82e5-29fd06000d41.png">

Would be great if it can be following the theme as it change to dark or light.

**Comment by diegoveloper** [comment]
You can change the color:
https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/lib/keyboard_actions.dart

KeyboardActionsConfig , keyboardBarColor

**Comment by jnickzlim** [comment]
Yes, we can change the color of the bar, however when we switch the theme to dark, the IconButton color changes too:

**Light Theme: icon button color black (White would look so much better)**
<img width="370" alt="Screenshot 2019-07-25 at 10 14 54 AM" src="https://user-images.githubusercontent.com/35293490/61840837-1ecc3300-aec5-11e9-8822-5b6b0c98ce78.png">

**Dark theme: icon button color white (This looks fine)**
<img width="365" alt="Screenshot 2019-07-25 at 10 15 07 AM" src="https://user-images.githubusercontent.com/35293490/61840838-1f64c980-aec5-11e9-961b-e32a88daa298.png">

This will make setting a single bar color looks wired as shown above for the light theme.

**Comment by diegoveloper** [comment]
Hmm ok I could add a new parameter, iconColor . What do you think?

**Comment by jnickzlim** [comment]
Great, that will solve the theme switching icon button color issue.

**Comment by diegoveloper** [comment]
I pushed some changes, now you can use themes for the icon colors, like this:

```dart
Theme(
        data: Theme.of(context).copyWith(
          disabledColor: Colors.grey,
          iconTheme: IconTheme.of(context).copyWith(color: Colors.black),
        ),
        child: FormKeyboardActions(
          child: Content(),
        ),
      ),
```

if you don't care about disabledColor, use this:

```dart
IconTheme(
        data: IconTheme.of(context).copyWith(color: Colors.red),
        child: FormKeyboardActions(
          child: Content(),
        ),
      ),
```

**Comment by jnickzlim** [comment]
I have tested it, it's working. Thank you for the update! =)

**Comment by diegoveloper** [comment]
Ok great! , I publish the new version `2.1.2`  , thanks for the feedback

**Comment by kinex** [comment]
The problem with using `IconTheme` as suggested is that it effects also the child widget (it styles any `Icons` in your child widget using the same theme which you wanted to apply only to the keyboard actions).

**Comment by diegoveloper** [comment]
Could you add an example with this scenario?

**Comment by kinex** [comment]
If you declare your layout e.g. like this:
```dart
IconTheme(
  data: IconTheme.of(context).copyWith(color: Colors.red),
  child: FormKeyboardActions(
    child: Content(),
  ),
),
```
the given root widget `IconTheme` is applied to all child widgets including `FormKeyboardActions`, `Content()` and all of its children recursively. If your `Content` includes `Icons`, `ListTiles` or e.g. `TextFields` with a prefix icon, all of them get a wrong color.

So I think it would be better to have the `Color` parameter or `IconThemeData` parameter. If `IconThemeData` is passed as a parameter you can limit its scope only to the keyaboard action buttons. For comparison, see e.g. `actionsIconsTheme `parameter in the widget `SliverAppBar`.

**Comment by diegoveloper** [comment]
Would you mind sending a PR with those changes? I'm a little busy these weeks

**Comment by kinex** [comment]
I would like to help but currently busy too.... maybe later.
