### ISSUE TITLE
flutter: Another exception was thrown

### ISSUE THREAD

**Issue by Jungley8** [diegoveloper/flutter_keyboard_actions#33]
flutter: Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 2193 pos 12: 'child.parent == this': is not true.

Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (9 days ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0

**Comment by diegoveloper** [comment]
Add a simple code to reproduce the issue. Thanks
