### ISSUE TITLE
CupertinoPageScaffold

### ISSUE THREAD

**Issue by 330676687** [diegoveloper/flutter_keyboard_actions#36]
Does not support CupertinoPageScaffold?

**Comment by diegoveloper** [comment]
Hmm it should work, what error do you get?

**Comment by 330676687** [comment]
No log, just widgets are not displayed on the device

**Comment by 330676687** [comment]
code
` @override
  Widget build(BuildContext context) {
    if (Platform.isAndroid) {
    return Scaffold(
      backgroundColor: Color(0xFFF6F6F6),
      appBar: AppBar(
        elevation: 0,
        title: Text('离职员工'),
      ),
      body: FormKeyboardActions(
        child: Content(),
      ),
      resizeToAvoidBottomInset: false,
    );
    } else {
      return CupertinoPageScaffold(
        backgroundColor: Color(0xFFF6F6F6),
        navigationBar: CupertinoNavigationBar(
          backgroundColor: Colors.white,
          middle: Text('离职员工'),
          previousPageTitle: '返回',
          border: null,
        ),
        child: FormKeyboardActions(
          child: Content(),
        ),
        resizeToAvoidBottomInset: false,
      );
    }
  }`

**Comment by 330676687** [comment]
code
```
@override
  Widget build(BuildContext context) {
    if (Platform.isAndroid) {
    return Scaffold(
      backgroundColor: Color(0xFFF6F6F6),
      appBar: AppBar(
        elevation: 0,
        title: Text('离职员工'),
      ),
      body: FormKeyboardActions(
        child: Content(),
      ),
      resizeToAvoidBottomInset: false,
    );
    } else {
      return CupertinoPageScaffold(
        backgroundColor: Color(0xFFF6F6F6),
        navigationBar: CupertinoNavigationBar(
          backgroundColor: Colors.white,
          middle: Text('离职员工'),
          previousPageTitle: '返回',
          border: null,
        ),
        child: FormKeyboardActions(
          child: Content(),
        ),
        resizeToAvoidBottomInset: false,
      );
    }
  }
```

**Comment by diegoveloper** [comment]
Actually, I saw the error log and it's fixed now.

Use the dependency in this way until you confirm it's working :

```json
keyboard_actions:
    git: 
      url: git://github.com/diegoveloper/flutter_keyboard_actions.git
      ref: master
```

Let me know if it's working for you

**Comment by 330676687** [comment]
I just found out it's my problem. Sorry😂
