### ISSUE TITLE
Going out of the TextField with the Back button on device doesn't close the header

### ISSUE THREAD

**Issue by hyperpanthera** [diegoveloper/flutter_keyboard_actions#39]
The closeWidget & onTapAction closes it but not if you leave it with the device's back button. The keyboard vanishes but not the header.

Android, Samsung S7 Edge.

![alt text](https://i.imgur.com/M5gyLSh.jpg"Image")

**Comment by diegoveloper** [comment]
I sent some changes.
Use the dependency in this way until you confirm it's working :

```json
keyboard_actions:
    git: 
      url: git://github.com/diegoveloper/flutter_keyboard_actions.git
      ref: master
```

Let me know if it's working for you

**Comment by hyperpanthera** [comment]
@diegoveloper Works! Good job.

**Comment by CleImb** [comment]
I have the same problem nowadays. When I go out of a TextField with the Back button, the keyboard close but not the footer.
