### ISSUE TITLE
Keyorad not show in ios

### ISSUE THREAD

**Issue by nguyennp** [diegoveloper/flutter_keyboard_actions#5]
Using silmulator IPhone XR, the keyboard not shown.
![image](https://user-images.githubusercontent.com/23489987/51087328-78b8a700-1784-11e9-9ded-ae10a1698f1d.png)

**Comment by diegoveloper** [comment]
Select your iOS Simulator , on the top menu , Hardware | Keyboard | Toggle Software Keyboard
