### ISSUE TITLE
border or background shadow option

### ISSUE THREAD

**Issue by aimsugita** [diegoveloper/flutter_keyboard_actions#58]
hello
can you add the border line option?
or, hope background shadow option.
![fix](https://user-images.githubusercontent.com/55073526/70981239-21d7f200-20f8-11ea-94e6-938a140bc9ea.png)

**Comment by diegoveloper** [comment]
`keyboardSeparatorColor` was added, check the sample:

https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/example/lib/sample.dart
