### ISSUE TITLE
animation down to up

### ISSUE THREAD

**Issue by aimsugita** [diegoveloper/flutter_keyboard_actions#61]
Can you animate  the parts from down to up?
It appears before keyboard is finish moving.

<img width="207" alt="スクリーンショット 2019-12-18 16 06 33" src="https://user-images.githubusercontent.com/55073526/71063634-6d4dd700-21b0-11ea-9a54-ab531c4a3d1f.png">

**Comment by diegoveloper** [comment]
is not in the plan yet, but it's open if anyone want to contribute with it

**Comment by aimsugita** [comment]
@diegoveloper okey, someday.
