### ISSUE TITLE
Firing Keyboard with custom form by pressing a fab

### ISSUE THREAD

**Issue by YasQaisi** [diegoveloper/flutter_keyboard_actions#62]
Hello, As the title says, I'm trying to open up the keyboard with custom actions that will ask the user to enter some info and then will be saved in the database,

The problem is that I want the keyboard to be shown when the user presses a Fab - or a button ,

In the example I found that keyboard will be shown if a user presses a TextField.

is there any way to open up the keyboard with custom actions using a button? any hint will be great so I can achieve it.

this is an example to the thing I'm trying to explain

![WhatsApp Image 2019-12-20 at 10 11 48 PM](https://user-images.githubusercontent.com/29073531/71285301-e34f6b00-2375-11ea-8209-5a1035266549.jpeg)

Thank you for this amazing Lib.

**Comment by diegoveloper** [comment]
Hmm I guess if you already have a FocusNode as variable, you can use
focusNode.requestFocus() method.

**Comment by YasQaisi** [comment]
So you mean I put the textField in the custom footer of your lib and request the focus of that textField when the user pressed the fab and this will make the keyboard appear ?

sorry for my bad English :)

**Comment by diegoveloper** [comment]
Try adding a minimum sample code in just one file that I could run here, to
reproduce the issue. And I could help.

**Comment by YasQaisi** [comment]
Here is The Code
My Fab
```
FloatingActionButton(
          elevation: 4.0,
          onPressed: () {
            _nodeText1.requestFocus();
          },
          backgroundColor: Color(0xff00A78F),
          child: Icon(
            Icons.add,
            size: 32,
            color: Colors.white,
          ),
        ),
```


my Keyboard Config

```
KeyboardActionsConfig _buildConfig(BuildContext context) {
    return KeyboardActionsConfig(
        keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
        keyboardBarColor: Colors.grey[200],
        actions: [
          KeyboardAction(
            displayActionBar: false,
            focusNode: _nodeText1,
            footerBuilder: (_) => PreferredSize(
                child: Column(
                  children: <Widget>[
                    SizedBox(
                        height: 40,
                        child: Center(
                          child: Text('Custom Footer'),
                        )),
                    TextField(
                      focusNode: _nodeText1,
                      autofocus: true,
                    ),
                  ],
                ),
                preferredSize: Size.fromHeight(40)),
          ),
        ]);
  }
```

**Comment by diegoveloper** [comment]
Does it works?

**Comment by YasQaisi** [comment]
No, Nothing Happens when I press the Fab.

**Comment by diegoveloper** [comment]
did you set the `_nodeText1` in a textfield? because the keyboard should be
tied to a textfield

**Comment by YasQaisi** [comment]
yes it is in the Code I provided, under the Custom Footer, do you have the same issue ?
```
PreferredSize(
                child: Column(
                  children: <Widget>[
                    SizedBox(
                        height: 40,
                        child: Center(
                          child: Text('Custom Footer'),
                        )),
                    TextField(
                      focusNode: _nodeText1,
                      autofocus: true,
                    ),
                  ],
                ),
                preferredSize: Size.fromHeight(40)),
          ),
```

**Comment by diegoveloper** [comment]
It works for me, check the sample :  https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/example/lib/sample.dart
![sample1](https://user-images.githubusercontent.com/4898256/71290153-2214ff00-233d-11ea-8d6e-8dc753ee89ef.gif)

**Comment by YasQaisi** [comment]
The TextField I want to have is inside the Action itself, I'm sorry I did not give a GIF from the beginning,

Here
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/29073531/71290623-57434080-2381-11ea-9a98-f3d2f3da30ae.gif)


thanks for your patience

**Comment by diegoveloper** [comment]
Ok, I guess you don't need this package on that case, I made a sample for you . 
![sample](https://user-images.githubusercontent.com/4898256/71293425-5b506d80-2343-11ea-9711-f60c23aae2a6.gif)

code:

```dart
class HomePageState extends State<HomePage> {
  bool visible = false;
  final focusNode = FocusNode();

  @override
  void initState() {
    focusNode.addListener(() {
      if (!focusNode.hasFocus) {
        setState(() {
          visible = false;
        });
      }
    });
    super.initState();
  }

  @override
  void dispose() {
    focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          setState(() {
            visible = true;
          });
        },
      ),
      body: Column(
        children: [
          Expanded(
            child: Container(
              color: Colors.red,
            ),
          ),
          if (visible)
            Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
              Padding(
                padding: const EdgeInsets.all(12.0),
                child: TextField(
                  focusNode: focusNode,
                  autofocus: true,
                  decoration: InputDecoration(labelText: "Input here"),
                ),
              ),
              Row(
                children: [
                  OutlineButton(
                    child: Text("action 1"),
                    onPressed: () => null,
                  ),
                  OutlineButton(
                    child: Text("action 2"),
                    onPressed: () => null,
                  )
                ],
              ),
            ]),
        ],
      ),
    );
  }
}
```

**Comment by YasQaisi** [comment]
Thanks, it works just fine :)
