### ISSUE TITLE
Autoscrolling does not work with SingleChildScrollView

### ISSUE THREAD

**Issue by kinex** [diegoveloper/flutter_keyboard_actions#65]
If I add a `Column` with `TextField`s into `SingleChildScrollView`, `TextField`s are not scrolled automatically into view. Using `ListView` fixes the issue, but it cannot be used due to https://github.com/flutter/flutter/issues/11500. 

Another workaround is to replace `SingleChildScrollView` directly with its child (`Column` in my case), but this would require extra logic especially if you are planning to use this plugin only with iOS and not with Android.

So as an improvement, shouldn't the related logic starting from here https://github.com/diegoveloper/flutter_keyboard_actions/blob/62064b8c487f4a1606bab756f83921398c4b17db/lib/external/bottom_area_avoider.dart#L89 check if the child is already a `SingleChildScrollView`? Now it will wrap an existing `SingleChildScrollView` with another `SingleChildScrollView`. I guess this causes the issue.

**Comment by diegoveloper** [comment]
Could you add a minimum sample code to reproduce the issue?

**Comment by kinex** [comment]
After all I was not able to reproduce this with a minimal sample code with only `TextField`s wrapped to `SingleChildScrollView` / `Column`. I don't know what is causing this, but it doesn't work in my production app unless I remove the `SingleChildScrollView`. My production app view is of course much more complex, there are a lot of other widgets too in addition to `TextField`s. But I don't have more time to investigate this, so I will close this.

Nevertheless, I suggest you review that code and see if it can be refactored. At least I wouldn't like to have in my widget tree useless extra `SingleChildScrollView`s included. It won't at least improve performance and sounds like a source for other problems too.
