### ISSUE TITLE
Feature request: allow disabling and hiding Up/Down buttons in a specific TextField

### ISSUE THREAD

**Issue by kinex** [diegoveloper/flutter_keyboard_actions#66]
Sample form structure:
```
1. TextField
2. TextField
3. TextField
4. DropdownButtonFormField
5. DropdownButtonFormField
6. DropdownButtonFormField
7. TextField
8. TextField
9. TextField
```
In the `TextField` 3, I would like to disable Down-button (or preferably it should work like a Close-button) to prevent jumping directly to `TextField` 7 (user should go through the `DropDownButtonFormField`s first).

All or any of the following new features would help:
- Allow disabling Up/Down buttons in `KeyboardAction` 
- Allow hiding Up/Down buttons in `KeyboardAction`
- Allow customizing Up/Down buttons action in `KeyboardAction` so that it closes the keyboard instead of navigating Up/Down

**Comment by kinex** [comment]
I found a partial workaround which is to include this in `KeyboardActionsConfig` between 3/4 and 6/7:
```dart
KeyboardAction(
  focusNode: _ignoredFocusNode,
  displayActionBar: false,
)
```
There is still an issue if there is a single TextField between other types of widgets. In this case I would like to have there a Close-button only as there is nothing above or below to navigate to.

**Comment by diegoveloper** [comment]
I added a new property `displayArrows` inside `KeyboardAction`, could you try changing your pubspec pointing to the url of the repo? thanks

**Comment by kinex** [comment]
Seems to work as expected. Together wIth this enhancement and the "workaround" described above I can achieve what I want. Thank you!
