### ISSUE TITLE
The getter 'position' was called on null.

### ISSUE THREAD

**Issue by reachanil** [diegoveloper/flutter_keyboard_actions#67]
Hi,
I'm getting the below exception every time the keyboard changes from number only to text. I'm using the text fields in a list view which is a child of KeyboardActions and KeyboardActionsConfig.
Please help.
════════ Exception caught by scheduler library 
The following NoSuchMethodError was thrown during a scheduler callback:
The getter 'position' was called on null.
Receiver: null
Tried calling: position

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      scrollToObject (package:keyboard_actions/external/bottom_area_avoider.dart:189:33)
#2      BottomAreaAvoiderState._paddingAnimationStatusChanged.<anonymous closure> (package:keyboard_actions/external/bottom_area_avoider.dart:153:7)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1049:9)
...

**Comment by diegoveloper** [comment]
Could you add a minimum sample code to reproductive the issue?

**Comment by reachanil** [comment]
Hi, 
Thanks for the response. I was able to fix the issue by moving around the code a bit. 
Thanks a lot for the widget. It's very helpful! 
Closing the issue.

**Comment by SatYu26** [comment]
hello, I am facing the similar issue. can you explain what exactly u did to solve it.

**Comment by samuelematias** [comment]
> hello, I am facing the similar issue. can you explain what exactly u did to solve it.

I had the same problem, right now. I Fixed use the `autoScroll = true` and removing the another `SingleChildScrollView`/`LayoutBuilder` that i was using.
I hope it helps.

**Comment by larssn** [comment]
Could you reopen? It seems this is just a workaround to a bug in the code.

We're seeing the same problem, periodically. It ends up in our error reporting service, but that's it. The user experience is unaffected.

**Comment by diegoveloper** [comment]
Can you add a minimum code to reproduce the issue?

**Comment by larssn** [comment]
No, I cannot. It's highly periodic.

**Comment by toebgen** [comment]
I just ran into this issue as well. In case this might be helpful for anybody else, 
```
KeyboardActions(
  disableScroll: true,
  // ...
```
seems to help getting around this issue.
