### ISSUE TITLE
support multiple actions for a given text fields

### ISSUE THREAD

**Issue by ekuleshov** [diegoveloper/flutter_keyboard_actions#68]
The iOS api allows to add multiple arbitrary keyboard actions (e.g. Save or Go and Cancel), but flutter_keyboard_actions is restricting it to only one action per field, so I don't see a way to have both cancel and save actions, especially for a numeric-only keyboard on the phone.

Please extend api to allow multiple actions, e.g. introduce another constructor in `KeyboardAction` that would accept list of `focusNodes` and have `child` instead of `closeWidget`.

**Comment by diegoveloper** [comment]
Could you add a screenshot about what you want?

**Comment by ekuleshov** [comment]
You can see example with multiple toolbar items at https://medium.com/@thedan84/how-to-set-up-a-keyboard-input-accessory-view-programmatically-4f78f0420351

In ios you can write something like this. Note multiple toolbar items:

```
let bar = UIToolbar()
let reset = UIBarButtonItem(title: "Reset", style: .plain, target: self, action: #selector(resetTapped))
bar.items = [ reset ]
bar.sizeToFit()
textField.inputAccessoryView = bar
```

**Comment by diegoveloper** [comment]
Ok, thanks for the sample , I'll check it out

**Comment by diegoveloper** [comment]
Hey, I've just pushed some changes into `master` , could you try using the package like this? 

```
  keyboard_actions: 
    git: 
      url: git://github.com/diegoveloper/flutter_keyboard_actions.git
      ref: master 
```

And check the samples updated.  

It has some breaking changes so , would you like to help me test this feature before release? Thanks :)

![Uploading Simulator Screen Shot - iPhone 8 - 2020-01-16 at 18.42.52.png…]()

**Comment by diegoveloper** [comment]
@ekuleshov did you try?

**Comment by kinex** [comment]
It would be great to allow fully customizing the whole toolbar and not just buttons on the right. Few layout samples I would need in my app:

left: configureButton | up - down, right: Done
left: speedButton1, speedButton2, speedButton3, right: Done
left: up - down, center: speedButton , right: Done
left: configureButton, right: down, Done
left: speedButton1, speedButton2, speedButton3, right: down, Done

So there could be something like `leftButtons`, `centerButtons `and `rightButtons` or allow building the whole toolbar widget with possibility to add up/down/done -buttons where wanted.

**Comment by diegoveloper** [comment]
@kinex could you open another issue ?

**Comment by kinex** [comment]
Added https://github.com/diegoveloper/flutter_keyboard_actions/issues/72#issue-563913377
