### ISSUE TITLE
add support for web and macos platforms

### ISSUE THREAD

**Issue by ekuleshov** [diegoveloper/flutter_keyboard_actions#69]
Please add support for web and macos platforms

**Comment by diegoveloper** [comment]
what's the error you have?

**Comment by ekuleshov** [comment]
The https://pub.dev/packages/keyboard_actions says only android and ios are supported.

E.g. compare with https://pub.dev/packages/shared_preferences - it listed with support for the web platfrom

**Comment by diegoveloper** [comment]
yeah this was built before flutter web, but could you try running the
example in flutter web?

**Comment by ekuleshov** [comment]
My app needs some other dependencies, so I can't try it at the moment and dart pad doesn't allow keyboard_actions plugin.

I assumed it needed some descriptor for pub.dev site to allow building depending apps.

**Comment by diegoveloper** [comment]
Ok, I'll check this.

**Comment by diegoveloper** [comment]
it can compile on web now
