### ISSUE TITLE
Remove Android/iOS plugin code

### ISSUE THREAD

**Issue by MisterJimson** [diegoveloper/flutter_keyboard_actions#7]
Looks like this can be a pure dart package with no native code needed.

These can be removed

https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/ios/Runner/GeneratedPluginRegistrant.h
https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/ios/Runner/GeneratedPluginRegistrant.m

**Comment by diegoveloper** [comment]
Fixed on 2.0.0
