### ISSUE TITLE
System Keyboard Support?

### ISSUE THREAD

**Issue by suragch** [diegoveloper/flutter_keyboard_actions#70]
I'm very interested in your project. I was playing around with your example app and looking at the source code to understand how this works. As I understand it, the `KeyboardCustomInput` is a way to make a custom keyboard that you can use within your own flutter app, but it is not a way to make a system keyboard. Is that correct? If so, what would it take to make Android and iOS system keyboards in Flutter?

**Comment by diegoveloper** [comment]
You will have to do it in native code.
