### ISSUE TITLE
Enhance toolbar customization options

### ISSUE THREAD

**Issue by kinex** [diegoveloper/flutter_keyboard_actions#72]
It would be great to allow fully customizing the whole toolbar and not just the buttons on the right. Few samples:

left: configureButton | up - down, right: Done
left: speedButton1, speedButton2, speedButton3, right: Done
left: up - down, center: speedButton , right: Done
left: configureButton, right: down, Done
left: speedButton1, speedButton2, speedButton3, right: down, Done

So there could be something like leftButtons, centerButtons and rightButtons or allow building the whole toolbar widget with possibility to add up/down/done -buttons where wanted. 

As available space is limited the up-button is not very important in my opinion (you can easily tap a field in up-direction anyway). In my app I would prefer having down- and done-buttons and possibly some speed buttons in specific fields (to allow e.g. quickly entering a previously used value).

**Comment by GroovinChip** [comment]
@diegoveloper any plans to implement this?

**Comment by diegoveloper** [comment]
@GroovinChip hmmm I think it could be covered with the latest changes, see this file :

https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/lib/keyboard_action.dart

You can specify a `toolbarButtons` and you could add the buttons you want, also if you have access to the focusNode , you can easily create your  `prev` ,`next` buttons.

**Comment by GroovinChip** [comment]
I'm already using `KeyboardAction`, what I'm curious about is if there's a way to specify where on the toolbar I can place my actions. For example, I'd like to have one action anchored to the right, and other actions anchored to the left. Kind of like the 'New Tweet' screen in the Android (probably iOS too) Twitter app.

**Comment by diegoveloper** [comment]
Do you mean something like this? https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/example/lib/sample2.dart

**Comment by GroovinChip** [comment]
Yes, exactly that. Thank you!

**Comment by GroovinChip** [comment]
@diegoveloper what's the proper way to get the content of the text field in the custom footer widget?

**Comment by diegoveloper** [comment]
Hmm those are separated widgets , why do you need the context?  Check these
examples :
https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/example/lib/content.dart#L241

**Comment by GroovinChip** [comment]
I need it because I've got a button that publishes the content of my textfield to an API

**Comment by diegoveloper** [comment]
Ok, run the samples and the `KeyboardCustomInput` components

**Comment by GroovinChip** [comment]
KeyboardCustomInput is for a custom keyboard, right? That's not really what I need. Here's a screenshot of my UI:
![Screenshot_20200316-184217](https://user-images.githubusercontent.com/4250470/76805788-27f07400-67b6-11ea-9f03-92d32419d0be.png)

**Comment by diegoveloper** [comment]
You are right! , sorry, let me prepare an example

**Comment by diegoveloper** [comment]
@GroovinChip sample updated, https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/example/lib/sample2.dart

**Comment by GroovinChip** [comment]
Obviously pass the controller, I feel so dumb lol! Thanks!
