### ISSUE TITLE
Widgets inside keyboardActions invisible/lower layer

### ISSUE THREAD

**Issue by mrgithub** [diegoveloper/flutter_keyboard_actions#74]
When I wrap a widget thats nested deep in a stack widget then it disappears..  I cant see it and I cant click it.  I suspect its under the layers as the focus node for that widget does activate.  If I comment out the keyboard code and hot refresh then i can see the control.  Maybe its just a z index issue - is there a way to set the z index/layer level on controls under it in the widget tree?

**Comment by diegoveloper** [comment]
Try reproducing the issue in a single file that I could run here.

**Comment by mrgithub** [comment]
import 'package:flutter/material.dart';
import 'package:keyboard_actions/keyboard_actions.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Widget> movableItems = [];

  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      movableItems.add(MoveableTextItem(
          key: UniqueKey(),
          onDelete: (Key k) {
            setState(() {
              movableItems.removeWhere((item) => item.key == k);
            });
          }));
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Stack(
        children: movableItems,
      ),

      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class MoveableTextItem extends StatefulWidget {
  final Function(Key) onDelete;

  const MoveableTextItem({Key key, this.onDelete}) : super(key: key);
  @override
  MoveableTextItemState createState() => new MoveableTextItemState();
}

class MoveableTextItemState extends State<MoveableTextItem> {
  double xPosition = 50;
  double yPosition = 50;
  double fontSize = 40;

  String dropdownValue = 'One';

  final TextEditingController controller = new TextEditingController();

  final FocusNode _nodeText1 = FocusNode();
  final FocusNode _nodeText2 = FocusNode();
  final custom2Notifier = ValueNotifier<Color>(Colors.blue);

  KeyboardActionsConfig _buildConfig(BuildContext context) {
    return KeyboardActionsConfig(
        keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
        keyboardBarColor: Colors.grey[200],
        nextFocus: true,
        actions: [
          KeyboardAction(
            focusNode: _nodeText1,
            // displayCloseWidget: true,
            footerBuilder: (_) => MyPickerKeyboard2(
              notifier: custom2Notifier,
            ),
          ),
          KeyboardAction(
            focusNode: _nodeText2,
//            closeWidget: Padding(
//              padding: EdgeInsets.all(8.0),
//              child: Icon(Icons.close),
//            ),
          ),
        ]);
  }

  @override
  void initState() {
    // color = RandomColor().randomColor();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Positioned(
      top: yPosition,
      left: xPosition,
      child: GestureDetector(
        onPanUpdate: (tapInfo) {
          setState(() {
            xPosition += tapInfo.delta.dx;
            yPosition += tapInfo.delta.dy;
          });
        },
        child: ConstrainedBox(
          constraints: new BoxConstraints(
            minWidth: 5,
            maxHeight: MediaQuery.of(context).size.height * 0.8,
            maxWidth: MediaQuery.of(context).size.width * 0.8,
          ),
          child: Column(children: <Widget>[


              //****Uncomment the 3 lines below to enable the keyboard 
//            KeyboardActions(
//              config: _buildConfig(context),
//              child:


              TextField(
                  focusNode: _nodeText2,
                  cursorColor: Colors.red,
                  expands: false,
                  cursorRadius: Radius.circular(8.0),
                  cursorWidth: 8.0,
                  autofocus: true,
                  keyboardType: TextInputType.multiline,
                  textAlign: TextAlign.center,
                  maxLines: null, //unlimited lines
                  controller: controller,
                  decoration: InputDecoration(
                    border: OutlineInputBorder(),
                    hintText: "Write here..",
                  ),
                  style: TextStyle(
                    color: Colors.red,
                    fontSize: fontSize,
                  )),

            //****Uncomment the 1 lines below to enable the keyboard 
//            ),

          ]),
        ),
      ),
    );
  }
}

// A quick example "keyboard" widget for picking a color.
class MyPickerKeyboard2 extends StatelessWidget
    with KeyboardCustomPanelMixin<Color>
    implements PreferredSizeWidget {
  final ValueNotifier<Color> notifier;
  static const double _kKeyboardHeight = 200;

  MyPickerKeyboard2({Key key, this.notifier}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final double rows = 3;
    final double screenWidth = MediaQuery.of(context).size.width;
    final int colorsCount = Colors.primaries.length;
    final int colorsPerRow = (colorsCount / rows).ceil();
    final double itemWidth = screenWidth / colorsPerRow;
    final double itemHeight = _kKeyboardHeight / rows;

    return Container(
        height: _kKeyboardHeight,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Text(
                'Headline',
                style: TextStyle(fontSize: 18),
              ),
              SizedBox(
                height: 200.0,
                child: ListView.builder(
                  physics: ClampingScrollPhysics(),
                  shrinkWrap: true,
                  scrollDirection: Axis.horizontal,
                  itemCount: 15,
                  itemBuilder: (BuildContext context, int index) => Card(
                    child: Center(child: Text('Dummy Card Text')),
                  ),
                ),
              ),
              Text(
                'Demo Headline 2',
                style: TextStyle(fontSize: 18),
              ),
              SizedBox(
                height: 200.0,
                child: ListView.builder(
                  physics: ClampingScrollPhysics(),
                  shrinkWrap: true,
                  scrollDirection: Axis.horizontal,
                  itemCount: 15,
                  itemBuilder: (BuildContext context, int index) => Card(
                    child: Center(child: Text('Dummy Card Text')),
                  ),
                ),
              ),
              Card(
                child: ListTile(
                    title: Text('Motivation $int'),
                    subtitle: Text('this is a description of the motivation')),
              ),
              Card(
                child: ListTile(
                    title: Text('Motivation $int'),
                    subtitle: Text('this is a description of the motivation')),
              ),
              Card(
                child: ListTile(
                    title: Text('Motivation $int'),
                    subtitle: Text('this is a description of the motivation')),
              ),
              Card(
                child: ListTile(
                    title: Text('Motivation $int'),
                    subtitle: Text('this is a description of the motivation')),
              ),
            ],
          ),
        ));
  }

  @override
  Size get preferredSize => Size.fromHeight(_kKeyboardHeight);
}

**Comment by mrgithub** [comment]
Code attached.  There's 4 lines that need uncommenting to allow the keyboard to appear.


[keyboard not appearing code.txt](https://github.com/diegoveloper/flutter_keyboard_actions/files/4210530/keyboard.not.appearing.code.txt)

**Comment by diegoveloper** [comment]
It's working fine for me, I just removed the Column widget.

```dart

  @override
  Widget build(BuildContext context) {
    return Positioned(
      top: yPosition,
      left: xPosition,
      child: GestureDetector(
        onPanUpdate: (tapInfo) {
          setState(() {
            xPosition += tapInfo.delta.dx;
            yPosition += tapInfo.delta.dy;
          });
        },
        child: ConstrainedBox(
          constraints: new BoxConstraints(
            minWidth: 5,
            maxHeight: MediaQuery.of(context).size.height * 0.8,
            maxWidth: MediaQuery.of(context).size.width * 0.8,
          ),
          child: KeyboardActions(
            config: _buildConfig(context),
            child: TextField(
                focusNode: _nodeText2,
                cursorColor: Colors.red,
                expands: false,
                cursorRadius: Radius.circular(8.0),
                cursorWidth: 8.0,
                autofocus: true,
                keyboardType: TextInputType.multiline,
                textAlign: TextAlign.center,
                maxLines: null, //unlimited lines
                controller: controller,
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  hintText: "Write here..",
                ),
                style: TextStyle(
                  color: Colors.red,
                  fontSize: fontSize,
                )),
          ),
        ),
      ),
    );
  }
}

```
