### ISSUE TITLE
Option to set overscroll of BottomAreaAvoider needed

### ISSUE THREAD

**Issue by jwoverland** [diegoveloper/flutter_keyboard_actions#77]
I’m using TextFormFields and the validation text is displayed behind the action bar because the bottom of the editable area scrolls even with the top of the action bar.  I believe if we could assign a value to the overscroll parameter of the BottomAreaAvoider it would scroll the extra needed to display the validation text.

![53A1F8B3-1783-4047-ABCF-041F40B29AA8](https://user-images.githubusercontent.com/60272555/77241968-adfe2780-6bc7-11ea-9407-9612932863d8.png)

**Comment by diegoveloper** [comment]
Yeah, that make sense, add a simple code to reproduce the issue and I will
see what I can do.

**Comment by jwoverland** [comment]
import 'package:flutter/material.dart';
import 'package:keyboard_actions/keyboard_actions.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final FocusNode _node1 = FocusNode();
  final FocusNode _node2 = FocusNode();
  final FocusNode _node3 = FocusNode();
  final FocusNode _node4 = FocusNode();
  final FocusNode _node5 = FocusNode();
  final FocusNode _node6 = FocusNode();
  final FocusNode _node7 = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: _testForm());
  }

  Widget _testForm() {
    return KeyboardActions(
        config: _buildTimeslipConfig(context),
        child: Form(
          autovalidate: true,
          // key: widget.formStateKey,
          child: SingleChildScrollView(
            // key: _timeslipKey,
            padding: EdgeInsets.all(16),
            child: Column(children: <Widget>[
              TextFormField(
                  focusNode: _node1,
                  keyboardType: TextInputType.numberWithOptions(
                      signed: false, decimal: true),
                  maxLines: 1,
                  decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      filled: true,
                      labelText: "Node 1"),
                  validator: (val) {
                    return val.length > 1 ? "Value Too Long" : null;
                  }),
              SizedBox(height: 24),
              TextFormField(
                  focusNode: _node2,
                  keyboardType: TextInputType.numberWithOptions(
                      signed: false, decimal: true),
                  maxLines: 1,
                  decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      filled: true,
                      labelText: "Node 2"),
                  validator: (val) {
                    return val.length > 1 ? "Value Too Long" : null;
                  }),
              SizedBox(height: 24),
              TextFormField(
                  focusNode: _node3,
                  keyboardType: TextInputType.numberWithOptions(
                      signed: false, decimal: true),
                  maxLines: 1,
                  decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      filled: true,
                      labelText: "Node 3"),
                  validator: (val) {
                    return val.length > 1 ? "Value Too Long" : null;
                  }),
              SizedBox(height: 24),
              TextFormField(
                  focusNode: _node4,
                  keyboardType: TextInputType.numberWithOptions(
                      signed: false, decimal: true),
                  maxLines: 1,
                  decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      filled: true,
                      labelText: "Node 4"),
                  validator: (val) {
                    return val.length > 1 ? "Value Too Long" : null;
                  }),
              SizedBox(height: 24),
              TextFormField(
                  focusNode: _node5,
                  keyboardType: TextInputType.numberWithOptions(
                      signed: false, decimal: true),
                  maxLines: 1,
                  decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      filled: true,
                      labelText: "Node 5"),
                  validator: (val) {
                    return val.length > 1 ? "Value Too Long" : null;
                  }),
              SizedBox(height: 24),
              TextFormField(
                  focusNode: _node6,
                  keyboardType: TextInputType.numberWithOptions(
                      signed: false, decimal: true),
                  maxLines: 1,
                  decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      filled: true,
                      labelText: "Node 6"),
                  validator: (val) {
                    return val.length > 1 ? "Value Too Long" : null;
                  }),
              SizedBox(height: 24),
              TextFormField(
                  focusNode: _node7,
                  keyboardType: TextInputType.numberWithOptions(
                      signed: false, decimal: true),
                  maxLines: 1,
                  decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      filled: true,
                      labelText: "Node 7"),
                  validator: (val) {
                    return val.length > 1 ? "Value Too Long" : null;
                  }),
              SizedBox(height: 24),
            ]),
          ),
        ));
  }

  KeyboardActionsConfig _buildTimeslipConfig(BuildContext context) {
    return KeyboardActionsConfig(
      keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
      nextFocus: true,
      actions: [
        KeyboardAction(focusNode: _node1, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              color: Colors.black,
              onPressed: () => node.unfocus(),
            );
          },
        ]),
                KeyboardAction(focusNode: _node2, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              color: Colors.black,
              onPressed: () => node.unfocus(),
            );
          },
        ]),
                KeyboardAction(focusNode: _node3, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              color: Colors.black,
              onPressed: () => node.unfocus(),
            );
          },
        ]),
                KeyboardAction(focusNode: _node4, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              color: Colors.black,
              onPressed: () => node.unfocus(),
            );
          },
        ]),
                KeyboardAction(focusNode: _node5, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              color: Colors.black,
              onPressed: () => node.unfocus(),
            );
          },
        ]),
                KeyboardAction(focusNode: _node6, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              color: Colors.black,
              onPressed: () => node.unfocus(),
            );
          },
        ]),
                KeyboardAction(focusNode: _node7, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              color: Colors.black,
              onPressed: () => node.unfocus(),
            );
          },
        ]),
      ],
    );
  }
}

**Comment by jwoverland** [comment]
Sorry, closed by mistake

**Comment by jwoverland** [comment]
Here is a simple reproduction.  If you arrow down to node 6 and type more than two characters the validation text will be under the action bar.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-22 at 00 01 18](https://user-images.githubusercontent.com/60272555/77242782-5912df00-6bd0-11ea-9cda-8063ef7a856f.png)


```dart
import 'package:flutter/material.dart';
import 'package:keyboard_actions/keyboard_actions.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final FocusNode _node1 = FocusNode();
  final FocusNode _node2 = FocusNode();
  final FocusNode _node3 = FocusNode();
  final FocusNode _node4 = FocusNode();
  final FocusNode _node5 = FocusNode();
  final FocusNode _node6 = FocusNode();
  final FocusNode _node7 = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: _testForm());
  }

  Widget _testForm() {
    return KeyboardActions(
        config: _buildTimeslipConfig(context),
        child: Form(
          autovalidate: true,
          // key: widget.formStateKey,
          child: SingleChildScrollView(
            // key: _timeslipKey,
            padding: EdgeInsets.all(16),
            child: Column(children: <Widget>[
              TextFormField(
                  focusNode: _node1,
                  keyboardType: TextInputType.numberWithOptions(
                      signed: false, decimal: true),
                  maxLines: 1,
                  decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      filled: true,
                      labelText: "Node 1"),
                  validator: (val) {
                    return val.length > 1 ? "Value Too Long" : null;
                  }),
              SizedBox(height: 24),
              TextFormField(
                  focusNode: _node2,
                  keyboardType: TextInputType.numberWithOptions(
                      signed: false, decimal: true),
                  maxLines: 1,
                  decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      filled: true,
                      labelText: "Node 2"),
                  validator: (val) {
                    return val.length > 1 ? "Value Too Long" : null;
                  }),
              SizedBox(height: 24),
              TextFormField(
                  focusNode: _node3,
                  keyboardType: TextInputType.numberWithOptions(
                      signed: false, decimal: true),
                  maxLines: 1,
                  decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      filled: true,
                      labelText: "Node 3"),
                  validator: (val) {
                    return val.length > 1 ? "Value Too Long" : null;
                  }),
              SizedBox(height: 24),
              TextFormField(
                  focusNode: _node4,
                  keyboardType: TextInputType.numberWithOptions(
                      signed: false, decimal: true),
                  maxLines: 1,
                  decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      filled: true,
                      labelText: "Node 4"),
                  validator: (val) {
                    return val.length > 1 ? "Value Too Long" : null;
                  }),
              SizedBox(height: 24),
              TextFormField(
                  focusNode: _node5,
                  keyboardType: TextInputType.numberWithOptions(
                      signed: false, decimal: true),
                  maxLines: 1,
                  decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      filled: true,
                      labelText: "Node 5"),
                  validator: (val) {
                    return val.length > 1 ? "Value Too Long" : null;
                  }),
              SizedBox(height: 24),
              TextFormField(
                  focusNode: _node6,
                  keyboardType: TextInputType.numberWithOptions(
                      signed: false, decimal: true),
                  maxLines: 1,
                  decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      filled: true,
                      labelText: "Node 6"),
                  validator: (val) {
                    return val.length > 1 ? "Value Too Long" : null;
                  }),
              SizedBox(height: 24),
              TextFormField(
                  focusNode: _node7,
                  keyboardType: TextInputType.numberWithOptions(
                      signed: false, decimal: true),
                  maxLines: 1,
                  decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      filled: true,
                      labelText: "Node 7"),
                  validator: (val) {
                    return val.length > 1 ? "Value Too Long" : null;
                  }),
              SizedBox(height: 24),
            ]),
          ),
        ));
  }

  KeyboardActionsConfig _buildTimeslipConfig(BuildContext context) {
    return KeyboardActionsConfig(
      keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
      nextFocus: true,
      actions: [
        KeyboardAction(focusNode: _node1, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              color: Colors.black,
              onPressed: () => node.unfocus(),
            );
          },
        ]),
                KeyboardAction(focusNode: _node2, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              color: Colors.black,
              onPressed: () => node.unfocus(),
            );
          },
        ]),
                KeyboardAction(focusNode: _node3, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              color: Colors.black,
              onPressed: () => node.unfocus(),
            );
          },
        ]),
                KeyboardAction(focusNode: _node4, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              color: Colors.black,
              onPressed: () => node.unfocus(),
            );
          },
        ]),
                KeyboardAction(focusNode: _node5, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              color: Colors.black,
              onPressed: () => node.unfocus(),
            );
          },
        ]),
                KeyboardAction(focusNode: _node6, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              color: Colors.black,
              onPressed: () => node.unfocus(),
            );
          },
        ]),
                KeyboardAction(focusNode: _node7, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              color: Colors.black,
              onPressed: () => node.unfocus(),
            );
          },
        ]),
      ],
    );
  }
}

```

**Comment by diegoveloper** [comment]
hi @jwoverland I exposed the `overscroll` property in `KeyboardActions` class, please use your pubspec.yml using my repository directly, my changes are in `master`, let me know if it works for you :)

**Comment by jwoverland** [comment]
I'm sorry to report that it didn't make any difference.

**Comment by diegoveloper** [comment]
Add the code you use, i tested and it is working fine.

Did you add overscroll property? Set it to 50.

**Comment by diegoveloper** [comment]
@jwoverland did you try the changes?

**Comment by jwoverland** [comment]
I did add the overscroll property and it didn’t have any effect.  What device are you testing on?

**Comment by diegoveloper** [comment]
iOS simulator, what value did you set?

**Comment by jwoverland** [comment]
I saw you had defaulted it to 12.  I tried 20 and then 50 and then 100.

**Comment by diegoveloper** [comment]
Ah sorry, I made some changes to your code :

Change this :

```dart

KeyboardActions(
config: _buildTimeslipConfig(context),
child: Form(
autovalidate: true,
// key: widget.formStateKey,
child: SingleChildScrollView(
// key: _timeslipKey,
padding: EdgeInsets.all(16),
child: Column(children: [
```

to this

```dart

 Form(
autovalidate: true,
// key: widget.formStateKey,
child: KeyboardActions(
config: _buildTimeslipConfig(context),
child: Column(children: [

```

**Comment by diegoveloper** [comment]
@jwoverland could you confirm it works ?

**Comment by jwoverland** [comment]
ok, I think the reason we are not seeing the same results is because we are taking different actions with the form.  The overscroll is working when, and only when setting focus on a textfield and the keyboard opens.  But if the keyboard is already displayed and you change focus using the next arrow it has the result in scrolling to the bottom of the textfield as pictured above.  If I close and reopen the keyboard the overscoll is again applied.

**Comment by diegoveloper** [comment]
hmm, could you add the code you are using?

**Comment by jwoverland** [comment]
Below is current code with screenshots in the following order:

1. After selecting node 1 and using next button to move to node 7
2. After activating validation text by entering two characters
3. Closing keyboard and reopening by tapping node 7 again 

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-24 at 20 30 17](https://user-images.githubusercontent.com/60272555/77492643-14c15200-6e0f-11ea-9dbb-c25b63fc24f6.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-24 at 20 30 31](https://user-images.githubusercontent.com/60272555/77492650-17bc4280-6e0f-11ea-9d49-0f04d47fb2a2.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-24 at 20 30 40](https://user-images.githubusercontent.com/60272555/77492652-19860600-6e0f-11ea-8667-432cc5462aaf.png)


```dart
import 'package:flutter/material.dart';
import 'package:keyboard_actions/keyboard_actions.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Overscroll Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Overscroll Test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final FocusNode _node1 = FocusNode();
  final FocusNode _node2 = FocusNode();
  final FocusNode _node3 = FocusNode();
  final FocusNode _node4 = FocusNode();
  final FocusNode _node5 = FocusNode();
  final FocusNode _node6 = FocusNode();
  final FocusNode _node7 = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        resizeToAvoidBottomInset: false,
        resizeToAvoidBottomPadding: false,
        appBar: AppBar(
          title: Text("Overscroll Test"),
        ),
        body: _testForm());
  }

  Widget _testForm() {
    return Form(
      autovalidate: true,
      child: KeyboardActions(
        overscroll: 50.0,
        config: _buildTimeslipConfig(context),
        child: Column(children: <Widget>[
          TextFormField(
              focusNode: _node1,
              keyboardType:
                  TextInputType.numberWithOptions(signed: false, decimal: true),
              maxLines: 1,
              decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  filled: true,
                  labelText: "Node 1"),
              validator: (val) {
                return val.length > 1 ? "Value Too Long" : null;
              }),
          SizedBox(height: 24),
          TextFormField(
              focusNode: _node2,
              keyboardType:
                  TextInputType.numberWithOptions(signed: false, decimal: true),
              maxLines: 1,
              decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  filled: true,
                  labelText: "Node 2"),
              validator: (val) {
                return val.length > 1 ? "Value Too Long" : null;
              }),
          SizedBox(height: 24),
          TextFormField(
              focusNode: _node3,
              keyboardType:
                  TextInputType.numberWithOptions(signed: false, decimal: true),
              maxLines: 1,
              decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  filled: true,
                  labelText: "Node 3"),
              validator: (val) {
                return val.length > 1 ? "Value Too Long" : null;
              }),
          SizedBox(height: 24),
          TextFormField(
              focusNode: _node4,
              keyboardType:
                  TextInputType.numberWithOptions(signed: false, decimal: true),
              maxLines: 1,
              decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  filled: true,
                  labelText: "Node 4"),
              validator: (val) {
                return val.length > 1 ? "Value Too Long" : null;
              }),
          SizedBox(height: 24),
          TextFormField(
              focusNode: _node5,
              keyboardType:
                  TextInputType.numberWithOptions(signed: false, decimal: true),
              maxLines: 1,
              decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  filled: true,
                  labelText: "Node 5"),
              validator: (val) {
                return val.length > 1 ? "Value Too Long" : null;
              }),
          SizedBox(height: 24),
          TextFormField(
              focusNode: _node6,
              keyboardType:
                  TextInputType.numberWithOptions(signed: false, decimal: true),
              maxLines: 1,
              decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  filled: true,
                  labelText: "Node 6"),
              validator: (val) {
                return val.length > 1 ? "Value Too Long" : null;
              }),
          SizedBox(height: 24),
          TextFormField(
              focusNode: _node7,
              keyboardType:
                  TextInputType.numberWithOptions(signed: false, decimal: true),
              maxLines: 1,
              decoration: InputDecoration(
                  border: OutlineInputBorder(),
                  filled: true,
                  labelText: "Node 7"),
              validator: (val) {
                return val.length > 1 ? "Value Too Long" : null;
              }),
          SizedBox(height: 24),
        ]),
      ),
    );
  }

  KeyboardActionsConfig _buildTimeslipConfig(BuildContext context) {
    return KeyboardActionsConfig(
      keyboardBarColor: Colors.blueGrey,
      keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
      nextFocus: true,
      actions: [
        KeyboardAction(focusNode: _node1, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              onPressed: () => node.unfocus(),
            );
          },
        ]),
        KeyboardAction(focusNode: _node2, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              onPressed: () => node.unfocus(),
            );
          },
        ]),
        KeyboardAction(focusNode: _node3, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              onPressed: () => node.unfocus(),
            );
          },
        ]),
        KeyboardAction(focusNode: _node4, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              onPressed: () => node.unfocus(),
            );
          },
        ]),
        KeyboardAction(focusNode: _node5, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              onPressed: () => node.unfocus(),
            );
          },
        ]),
        KeyboardAction(focusNode: _node6, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              onPressed: () => node.unfocus(),
            );
          },
        ]),
        KeyboardAction(focusNode: _node7, toolbarButtons: [
          (node) {
            return IconButton(
              icon: Icon(Icons.close),
              onPressed: () => node.unfocus(),
            );
          },
        ]),
      ],
    );
  }
}
```

**Comment by diegoveloper** [comment]
I tested your code and it's working fine. image attached 

- iOS simulator
- Flutter (Channel stable, v1.12.13+hotfix.8,)


![no_issue](https://user-images.githubusercontent.com/4898256/77496206-72a66780-6e18-11ea-9495-1fc0673920bc.gif)


run these commands:

- flutter clean
- flutter pub upgrade

**Comment by jwoverland** [comment]
you are not following the steps I described. Tab on node 1 and use the next arrow to move focus to node 7

**Comment by diegoveloper** [comment]
@jwoverland ok sorry about that. I sent new changes to master, could you try again?  flutter pub upgrade.

**Comment by jwoverland** [comment]
Seems to works some of the times now, but randomly:
![overscroll](https://user-images.githubusercontent.com/60272555/77506103-f705e400-6e32-11ea-8322-ceed0fc5fb20.gif)

**Comment by diegoveloper** [comment]
Hmm are you clicking fast? What about wait 1 second before press the arrow
button, just for testing.

**Comment by jwoverland** [comment]
Sorry for the poor GIF quality it is actually slower then it appears. I don't have a good tool for creating GIFs from screen recordings. It doesn't matter how fast or slow I click I get the same random results.  I suspect you will get them as well when you test it.

**Comment by diegoveloper** [comment]
I can't reproduce the issue . GIF attached
![no_issue](https://user-images.githubusercontent.com/4898256/77560987-2137c000-6e8c-11ea-8a9b-b492cb7c8728.gif)

**Comment by jwoverland** [comment]
I testing with v1.12.13+hotfix.8, iOS simulator (iPhone 11)

**Comment by diegoveloper** [comment]
That's weird, try iphone 8 simulator

**Comment by jwoverland** [comment]
It still occurs with iphone 8 (simulator) see GIF below.  It's random. 

A bit of good news though, I tested on my physical iPhone 6 plus and it works every time.  I'll have to locate a newer physical phone to test it on as well.

![overscroll_iphone8](https://user-images.githubusercontent.com/60272555/77605628-6a672e80-6ee3-11ea-8a3d-ddd8c80591cb.gif)

**Comment by diegoveloper** [comment]
ok, let me know what are the results. Also I would like to know what OS
version are you using for your iOS simulators?

**Comment by jwoverland** [comment]
You last update is working.  I just needed to run another flutter clean and flutter pub upgrade.

Thank you!

**Comment by diegoveloper** [comment]
new version updated
