### ISSUE TITLE
For complex layout this plugin is not working

### ISSUE THREAD

**Issue by HetalGohil** [diegoveloper/flutter_keyboard_actions#78]
RenderBox was not laid out: RenderDecoratedBox#dac9f relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  SizedBox-[GlobalKey#6664d] file:///D:/flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/keyboard_actions-3.2.1/lib/keyboard_actions.dart:523:20

i have tried many thing like wraping with container and give fix height..use expanded widget but no luck

**Comment by diegoveloper** [comment]
Hey, check some of the closed issues :  https://github.com/diegoveloper/flutter_keyboard_actions/issues?q=is%3Aissue+is%3Aclosed     

Because you can't replicate your issue in a simple file , I can't help you now. Try checking the link above.
