### ISSUE TITLE
customize position of close widget + keyboard doesn't close on second time

### ISSUE THREAD

**Issue by Nk54** [diegoveloper/flutter_keyboard_actions#8]
Hello,

First of all, thanks for this Widget 👍 

I'd like to align the close widget on the left as it is getting collapsed by the floating button. (is it possible to have a closeWidgetAlignment ? If the closeWidget is in a Container, you can bind the closeWidgetAlignment to the Row mainAxisAlignment, isn't it ?

Also, the panel shouldn't inherit of any margin or padding in my humble opinion. It would make it more easy because right now, if your root widget has a margin, it will be applied to the panel. (see screenshot below).

Ask me if you need further information.

![image](https://user-images.githubusercontent.com/13755220/54873625-114d5200-4dda-11e9-84cf-1c465dfeecc5.png)

I was obliged to remove the margin/padding and move them to the content of the FormKeyboardActions widget.
![image](https://user-images.githubusercontent.com/13755220/54873636-89b41300-4dda-11e9-8c34-455791d20ed7.png)

Final result (I faced an issue where tapping on the close, then focus again the TextField, which open the keyboard again : then tapping the close widget only close the KeyboardAction panel but not the keyboard : second screenshot)
![image](https://user-images.githubusercontent.com/13755220/54873677-f4198300-4ddb-11e9-9f60-4b24a7e8357b.png)
![image](https://user-images.githubusercontent.com/13755220/54873691-62f6dc00-4ddc-11e9-84a1-4ef740746780.png)

**Comment by diegoveloper** [comment]
You can hide the next and prev button, check the source code.

Also you can replace the close widget with any widget, I didn't test if you
can align it to the left. Try and let me know if it works for you.

I don't understand the last part about the standalone , could you give me a
sample?

Thanks

**Comment by diegoveloper** [comment]
@Nk54 Do you have more info about the issue?
