### ISSUE TITLE
"Done" button doesn't display very well on iPhone

### ISSUE THREAD

**Issue by macabeus** [diegoveloper/flutter_keyboard_actions#82]
Very thank you for this great package, but I think that I found a bug.
On some cases the `Done` button shows as white on a gray bar, so is hard to found and read that.

Would be possible to color it as black?

![image](https://user-images.githubusercontent.com/9501115/81798985-9462c780-9508-11ea-84a3-216d9340b4ef.png)

**Comment by diegoveloper** [comment]
Check this https://github.com/diegoveloper/flutter_keyboard_actions/issues/32
