### ISSUE TITLE
displayActionBar: false does not hide the bar above footer builder

### ISSUE THREAD

**Issue by lzhuor** [diegoveloper/flutter_keyboard_actions#84]
On iOS, Flutter 17.1

There is always an additional bar above the footer builder (custom keyboard). See the red box. Does anyone know how to remove it? 

![image](https://user-images.githubusercontent.com/14172220/82404028-cccb4e00-9a92-11ea-89bd-f6bc78b7abad.png)

**Comment by diegoveloper** [comment]
check this property : https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/lib/keyboard_action.dart#L29

**Comment by lzhuor** [comment]
@diegoveloper Sorry I should have mentioned in the issue. Yes, I did. The screenshot was taken with `displayActionBar: false` set.

**Comment by diegoveloper** [comment]
Could you share the code? a simple code that I could run in a main file

**Comment by lzhuor** [comment]
@diegoveloper, btw. Thank you for maintaining this library. It's very handy and helpful. ❤️ 

I am sorry. I found the issue was not caused by the action bar.

The additional space is from additional space within the footer. Please see screenshot attached:
![image](https://user-images.githubusercontent.com/14172220/82408915-2afe2e00-9a9f-11ea-9fc6-81ab281826d4.png)

It can be re-produced in the example code - `KeyboardCustomInput` with `_nodeText10`.

**Comment by diegoveloper** [comment]
so , did you fix the issue ?

**Comment by lzhuor** [comment]
@diegoveloper Nope. I didn't manage to remove the scrolling effect. If you run the examples on an Android device, you will see this additional space. 

I tried to adjust the height here: https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/example/lib/custom_input.dart#L118

It doesn't work well. Could you please give me some hint of where should I look into?

**Comment by diegoveloper** [comment]
Did you try in iOS? or the issue only happens in android?

**Comment by lzhuor** [comment]
@diegoveloper Just tried on iOS. It also happens for iOS. Fixed hardcode a zero padding. I will PR later today. Thank you for help!

**Comment by diegoveloper** [comment]
Ok so you fixed the issue then ? I'll wait for your PR :) thanks    you can
follow me on twitter  https://twitter.com/diegoveloper

**Comment by lzhuor** [comment]
@diegoveloper Thanks! A quick question before you go, does Custom keyboard support Flutter Material `TextField`? 

I tried it and it pops up two keyboard (one custom, one native):
![image](https://user-images.githubusercontent.com/14172220/82410120-d0b29c80-9aa1-11ea-8238-787f76a00d64.png)

**Comment by diegoveloper** [comment]
Yeah, don't use TextField because it has the native keyboard when you
focus, you don't need a textfield if you are going to create your custom
keyboard.

**Comment by lzhuor** [comment]
@diegoveloper Got you! Thanks!

**Comment by lzhuor** [comment]
@diegoveloper I managed to reproduce another similar issue:
https://github.com/diegoveloper/flutter_keyboard_actions/issues/85

**Comment by amorenew** [comment]
In my case, it was because of the logo at the bottom in **the same column** which contains my text field
