### ISSUE TITLE
How to disable bottom avoider?

### ISSUE THREAD

**Issue by lzhuor** [diegoveloper/flutter_keyboard_actions#88]
Hi @diegoveloper ,

I understand that there is a `BottomAvoider` widget to automatically adjust the height of Scaffold. 

May I know how to disable it? 
The reason I am asking is that I have buttons using `Positioned(bottom: 0)`. I want them to be hidden (stay at the bottom of the screen at the back of the Custom Keyboard) behind my custom keyboard when `focuNode` is focused (keyboard open)  

## When Input is unfocused:
![image](https://user-images.githubusercontent.com/14172220/82560834-cb8a4600-9ba4-11ea-90d7-c81f3367ed56.png)

## When Input is focused (**current**)
![image](https://user-images.githubusercontent.com/14172220/82560740-967df380-9ba4-11ea-9c84-5ce1b2d95cf7.png)

## When Input is focused (**desired**)
![image](https://user-images.githubusercontent.com/14172220/82561892-c4fcce00-9ba6-11ea-8b41-43ab216c2694.png)

**Comment by diegoveloper** [comment]
There is a property in the Scaffold, resizeToAvoidBottomInset
Set it to false.

**Comment by lzhuor** [comment]
@diegoveloper Yes, I already did which doesn't help.

**Comment by lzhuor** [comment]
@diegoveloper I was putting the buttons in a `Stack` with `Positioned(bottom: 0)`. It didn't work.

However, if I put them into a Column. It works well.

**Comment by diegoveloper** [comment]
Cool, you can close the issue now

**Comment by lzhuor** [comment]
@diegoveloper closed. Thank you!

**Comment by huangbinjie** [comment]
Hi, I also need this feature.

If `KeyboardActions` wrap `TextField`

```dart
KeyboardActions(
  config: config,
  child: TextField(scrollPadding: EdgeInsets.all(60))
)
```

This line will alway have a padding bottom while system keyboard is open.

https://github.com/diegoveloper/flutter_keyboard_actions/blob/cfb4ee1fe59366b8fcdf2e0031451f857abac007/lib/external/bottom_area_avoider.dart#L125

Is it possible to provide an attribute to set this padding or disable bottom avoider?

**Comment by diegoveloper** [comment]
Add minimum code to reproduce the issue, attach screenshot if it is possible
