### ISSUE TITLE
Skip next TextField when it's disabled

### ISSUE THREAD

**Issue by emersonsiega** [diegoveloper/flutter_keyboard_actions#9]
I have a situation where one of my TextFields can be disabled some times.
The problem I have is that the focus keep being put in that field when the user navigates with keyboard actions.

The image below shows that behavior.
Focus was in the `Nome` field and `CPF` field was disabled. When I navigate through the arrows, the focus is put inside `CPF`.

![image](https://user-images.githubusercontent.com/2227499/56044864-7d0a4700-5d16-11e9-90e4-f9a42707d9c7.png)

**Comment by diegoveloper** [comment]
Would be great if you can add a simple code to reproduce the issue.

Thanks

**Comment by diegoveloper** [comment]
Fixed in version `1.0.4` , now you can add a `enabled` attribute to your `KeyboardAction` .
