### ISSUE TITLE
There is an area appear between actions view and keyboard

### ISSUE THREAD

**Issue by kgb16** [diegoveloper/flutter_keyboard_actions#91]
There is an area appear between actions view and keyboard
ios12, 
device: iphone xr 
keyboard type: "TextInputType.number"

addition: iphone 6/7 is ok.

**Comment by diegoveloper** [comment]
Could you add the code to reproduce the issue and a screenshot too.

**Comment by kgb16** [comment]
![6349C896-E73E-4328-B560-E93DFC8B17EA](https://user-images.githubusercontent.com/4557136/82850957-da6c5200-9f30-11ea-8820-2d107479f8d3.jpeg)

**Comment by diegoveloper** [comment]
Could you add the code to reproduce the issue?
What version of the package are you using ?
Paste flutter doctor here

**Comment by kgb16** [comment]
class YZKeyboardUtil {
  List<FocusNode> nodes;
  YZKeyboardUtil({this.nodes});

  KeyboardActionsConfig closeActionsConfig(BuildContext context) {
    return KeyboardActionsConfig(
        keyboardActionsPlatform: KeyboardActionsPlatform.IOS,
        keyboardBarColor: Colors.red,//Colors.grey[200],
        keyboardSeparatorColor: Colors.green,
        nextFocus: showNextFocus(),
        actions: createKeyboardActions());
  }

  bool showNextFocus() {
    if (nodes.length > 1) return true;
    return false;
  }

  List<KeyboardAction> createKeyboardActions() {
    List<KeyboardAction> actions = [];
    nodes.forEach((node) {
      KeyboardAction action = KeyboardAction(
          focusNode: node,
          // displayActionBar: false,
          footerBuilder: (_) => PreferredSize(
              child: Container(height: 20, color: Colors.blue,), preferredSize: Size.fromHeight(20)),
          toolbarButtons: [
            (node) {
              return GestureDetector(
                onTap: () => node.unfocus(),
                child: Padding(
                  padding: EdgeInsets.fromLTRB(8, 0, 15, 0),
                  child: Text("关闭", style: TextStyle(color: Colors.black)),
                ),
              );
            }
          ]
          );
      actions.add(action);
    });
    return actions;
  }
}

**Comment by kgb16** [comment]
here is the code of config the keyboard

**Comment by diegoveloper** [comment]
Please, try to reproduce in a single file  that I could run here :
 main.dart   <--- .  and use gist to add the code : https://gist.github.com/

**Comment by kgb16** [comment]
https://gist.github.com/kgb16/c18c9bc9f59e4b47eb0ea29d963fe458

**Comment by kgb16** [comment]
The main.dart is the entry

**Comment by diegoveloper** [comment]
Just create one file  main.dart that I could run here,  reduce the problem
, try to replicate the issue in just one widget.

**Comment by kgb16** [comment]
I found that it is normal to run the same code in a new project, so it should be that other configurations of my application will affect the setting of keyboard additional area location.

**Comment by kgb16** [comment]
void _insertOverlay() {
    OverlayState os = Overlay.of(context);
    _inserted = true;
    _overlayEntry = OverlayEntry(builder: (context) {
      // Update and build footer, if any
      _currentFooter = (_currentAction.footerBuilder != null)
          ? _currentAction.footerBuilder(context)
          : null;
      final queryData = MediaQuery.of(context);
      return Positioned(
        bottom: queryData.viewInsets.bottom,
        left: 0,
        right: 0,


The problem is found in this place, the position of the keyboard additional view is wrong, and the actual position will be little then
"MediaQuery.of (context). viewInsets.bottom"

**Comment by diegoveloper** [comment]
again, add a simple `main.dart` file reproducing the issue.

**Comment by jhbiggs** [comment]
Right, so I took your advice to @kgb16 and created a simple main file.  No gap.  I reloaded it on my phone, gap is there.  The only things I took out were the shared preferences and Firebase references, those shouldn't affect it, right?  I'll put the main file in the gist at the link above. Here's what I end up with: 
![IMG_5887](https://user-images.githubusercontent.com/35543657/83183335-41cf0100-a0ed-11ea-8352-f4c9334f5ea1.png)


Any suggestions?

**Comment by diegoveloper** [comment]
Just a single file that I could run here,  no external dependencies, only
keyboard_actions.

**Comment by jhbiggs** [comment]
Ok, that's what I did below.  I'm not sure if the link works, never created a Gist before.

https://gist.github.com/jhbiggs/d9c2e815779a770fb682c83852fcc6e2.js

**Comment by diegoveloper** [comment]
it doesn't work, that's a js file

**Comment by jhbiggs** [comment]
This one?

<script src="https://gist.github.com/jhbiggs/d9c2e815779a770fb682c83852fcc6e2.js"></script>

**Comment by jhbiggs** [comment]
Or this one:

gist.github.com/jhbiggs/main.dart

**Comment by diegoveloper** [comment]
test yourself, click on the link and see the results

**Comment by diegoveloper** [comment]
is not working for me, maybe is private.

**Comment by jhbiggs** [comment]
Maybe because I don't have an enterprise account, I don't know.   Here is the page in case you can help that way:

import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'keyboard_action.dart';
import 'keyboard_actions_config.dart';
import 'keyboard_actions.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: SettingsPage(),
    );
  }
}

// // import 'package:firebase_storage/firebase_storage.dart';
// import 'package:cloud_firestore/cloud_firestore.dart';



class SettingsPage  extends StatefulWidget  {
  SettingsPage();


  @override
  _SettingsPageState createState() => _SettingsPageState();
}

class _SettingsPageState extends State<SettingsPage> /*with ChangeNotifier*/{
  _SettingsPageState();

 
  final nameTextController = TextEditingController();
  final timeNeededTextController = TextEditingController();
  bool _prefBath = false;
  String _prefName = "";
  int _prefTimeNeeded = 12;
  
  final _nodeText1 = FocusNode();
  final _nodeText2 = FocusNode();

  KeyboardActionsConfig _buildConfig(BuildContext context) {
    return KeyboardActionsConfig(
      keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
      keyboardBarColor: Colors.grey[200],
      nextFocus: true,
      keyboardSeparatorColor: Colors.black,
      actions: [
        KeyboardAction(
            focusNode: _nodeText1,
            displayArrows: true,
            displayDoneButton: false,
            displayActionBar: false),
        KeyboardAction(
          focusNode: _nodeText2,
          displayDoneButton: true,
          displayArrows: true,
        ),
      ],
    );
  }

  @override
  void dispose() {
    nameTextController.dispose();
    timeNeededTextController.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    _loadPrefs();
  }

  _loadPrefs() async {

    setState(() {
     
    });
  }

  Widget _pushSettings() {
    return Scaffold(
    
        appBar: AppBar(title: Text('Settings')),
        body: Center(
            child: Container(
          
                child: ListView(
          padding: const EdgeInsets.all(16.0),
          children: <Widget>[
            showBathOrShowerChoice(),
            Divider(height: 5.0),
            showNameChoice("What shall we call you?", "name",
                nameTextController, TextInputType.text),
            Divider(height: 5.0),
            showTimeNeededChoice(
                "How much time in minutes do you think you'll need?",
                "number of minutes",
                timeNeededTextController,
                TextInputType.number),
            Divider(height: 5.0),
            KeyboardActions(
              // isDialog: widget.isDialog,
              config: _buildConfig(context),
              child: Container(
                padding: const EdgeInsets.all(15.0),
                child: Center(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    mainAxisSize: MainAxisSize.min,
                    children: <Widget>[
                      TextField(
                        onChanged: (value) async {
                          setState(() {
                          
                          });
                        },
                        keyboardType: TextInputType.number,
                        focusNode: _nodeText2,
                        decoration: InputDecoration(
                          hintText: "$_prefTimeNeeded" ?? "enter minutes",
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
            showLogoutButton(),
            Divider(height: 5.0),
          ],
        ))));
  }

  Widget showBathOrShowerChoice() {
    return Padding(
        padding: EdgeInsets.fromLTRB(0.0, 45.0, 0.0, 0.0),
        child: SizedBox(
            height: 40.0,
            child: SwitchListTile(
              title: const Text(
                'I take baths.',
                style: TextStyle(
                  fontSize: 18,
                  color: Colors.blueAccent,
                ),
              ),
              value: _prefBath,
              onChanged: (bool value) async {
               
                setState(() {
                  _prefBath = value;
                 
                });
              },
            )));
  }

  Widget showNameChoice(String question, String answerHintText,
      TextEditingController controller, TextInputType inputType) {
    return Padding(
        padding: EdgeInsets.fromLTRB(0.0, 45.0, 0.0, 0.0),
        child: Column(
          children: <Widget>[
            SizedBox(
              height: 40.0,
              child: ListTile(
                title: Text("$question",
                    style: TextStyle(
                      fontSize: 18,
                      color: Colors.blueAccent,
                    )),
              ),
            ),
            SizedBox(
              height: 40.0,
              child: ListTile(
                title: TextField(
                    focusNode: _nodeText1,
                    onChanged: (string) {
                    
                    },
                    keyboardType: inputType,
                    controller: controller,
                    decoration: InputDecoration(
                      hintText: _prefName ?? answerHintText,
                    )),
              ),
            )
          ],
        ));
  }

  Widget showTimeNeededChoice(String question, String answerHintText,
      TextEditingController controller, TextInputType inputType) {
    return Padding(
      padding: EdgeInsets.fromLTRB(0.0, 45.0, 0.0, 0.0),
      child:
          // Column(
          //   children: <Widget>[
          SizedBox(
        height: 40.0,
        child: ListTile(
          title: Text("$question",
              maxLines: null,
              style: TextStyle(
                fontSize: 18,
                color: Colors.blueAccent,
              )),
        ),
      ),
    );
    // );
  }

  Widget showLogoutButton() {
    return Padding(
        padding: EdgeInsets.fromLTRB(0.0, 45.0, 0.0, 0.0),
        child: SizedBox(
          height: 40.0,
          child: RaisedButton(
              onPressed: () {
               
              },
              autofocus: true,
              clipBehavior: Clip.none,
              elevation: 5.0,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(30.0)),
              child: Text('Log Out',
                  style: TextStyle(
                    fontSize: 20.0,
                    color: Colors.white,
                  ))),
        ));
  }

  @override
  Widget build(BuildContext context) {
    return _pushSettings();
  }
}

**Comment by jhbiggs** [comment]
or better

```
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'keyboard_action.dart';
import 'keyboard_actions_config.dart';
import 'keyboard_actions.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: SettingsPage(),
    );
  }
}

// // import 'package:firebase_storage/firebase_storage.dart';
// import 'package:cloud_firestore/cloud_firestore.dart';



class SettingsPage  extends StatefulWidget  {
  SettingsPage();


  @override
  _SettingsPageState createState() => _SettingsPageState();
}

class _SettingsPageState extends State<SettingsPage> /*with ChangeNotifier*/{
  _SettingsPageState();

 
  final nameTextController = TextEditingController();
  final timeNeededTextController = TextEditingController();
  bool _prefBath = false;
  String _prefName = "";
  int _prefTimeNeeded = 12;
  
  final _nodeText1 = FocusNode();
  final _nodeText2 = FocusNode();

  KeyboardActionsConfig _buildConfig(BuildContext context) {
    return KeyboardActionsConfig(
      keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
      keyboardBarColor: Colors.grey[200],
      nextFocus: true,
      keyboardSeparatorColor: Colors.black,
      actions: [
        KeyboardAction(
            focusNode: _nodeText1,
            displayArrows: true,
            displayDoneButton: false,
            displayActionBar: false),
        KeyboardAction(
          focusNode: _nodeText2,
          displayDoneButton: true,
          displayArrows: true,
        ),
      ],
    );
  }

  @override
  void dispose() {
    nameTextController.dispose();
    timeNeededTextController.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    _loadPrefs();
  }

  _loadPrefs() async {

    setState(() {
     
    });
  }

  Widget _pushSettings() {
    return Scaffold(
    
        appBar: AppBar(title: Text('Settings')),
        body: Center(
            child: Container(
          
                child: ListView(
          padding: const EdgeInsets.all(16.0),
          children: <Widget>[
            showBathOrShowerChoice(),
            Divider(height: 5.0),
            showNameChoice("What shall we call you?", "name",
                nameTextController, TextInputType.text),
            Divider(height: 5.0),
            showTimeNeededChoice(
                "How much time in minutes do you think you'll need?",
                "number of minutes",
                timeNeededTextController,
                TextInputType.number),
            Divider(height: 5.0),
            KeyboardActions(
              // isDialog: widget.isDialog,
              config: _buildConfig(context),
              child: Container(
                padding: const EdgeInsets.all(15.0),
                child: Center(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    mainAxisSize: MainAxisSize.min,
                    children: <Widget>[
                      TextField(
                        onChanged: (value) async {
                          setState(() {
                          
                          });
                        },
                        keyboardType: TextInputType.number,
                        focusNode: _nodeText2,
                        decoration: InputDecoration(
                          hintText: "$_prefTimeNeeded" ?? "enter minutes",
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
            showLogoutButton(),
            Divider(height: 5.0),
          ],
        ))));
  }

  Widget showBathOrShowerChoice() {
    return Padding(
        padding: EdgeInsets.fromLTRB(0.0, 45.0, 0.0, 0.0),
        child: SizedBox(
            height: 40.0,
            child: SwitchListTile(
              title: const Text(
                'I take baths.',
                style: TextStyle(
                  fontSize: 18,
                  color: Colors.blueAccent,
                ),
              ),
              value: _prefBath,
              onChanged: (bool value) async {
               
                setState(() {
                  _prefBath = value;
                 
                });
              },
            )));
  }

  Widget showNameChoice(String question, String answerHintText,
      TextEditingController controller, TextInputType inputType) {
    return Padding(
        padding: EdgeInsets.fromLTRB(0.0, 45.0, 0.0, 0.0),
        child: Column(
          children: <Widget>[
            SizedBox(
              height: 40.0,
              child: ListTile(
                title: Text("$question",
                    style: TextStyle(
                      fontSize: 18,
                      color: Colors.blueAccent,
                    )),
              ),
            ),
            SizedBox(
              height: 40.0,
              child: ListTile(
                title: TextField(
                    focusNode: _nodeText1,
                    onChanged: (string) {
                    
                    },
                    keyboardType: inputType,
                    controller: controller,
                    decoration: InputDecoration(
                      hintText: _prefName ?? answerHintText,
                    )),
              ),
            )
          ],
        ));
  }

  Widget showTimeNeededChoice(String question, String answerHintText,
      TextEditingController controller, TextInputType inputType) {
    return Padding(
      padding: EdgeInsets.fromLTRB(0.0, 45.0, 0.0, 0.0),
      child:
          // Column(
          //   children: <Widget>[
          SizedBox(
        height: 40.0,
        child: ListTile(
          title: Text("$question",
              maxLines: null,
              style: TextStyle(
                fontSize: 18,
                color: Colors.blueAccent,
              )),
        ),
      ),
    );
    // );
  }

  Widget showLogoutButton() {
    return Padding(
        padding: EdgeInsets.fromLTRB(0.0, 45.0, 0.0, 0.0),
        child: SizedBox(
          height: 40.0,
          child: RaisedButton(
              onPressed: () {
               
              },
              autofocus: true,
              clipBehavior: Clip.none,
              elevation: 5.0,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(30.0)),
              child: Text('Log Out',
                  style: TextStyle(
                    fontSize: 20.0,
                    color: Colors.white,
                  ))),
        ));
  }

  @override
  Widget build(BuildContext context) {
    return _pushSettings();
  }
}```

**Comment by diegoveloper** [comment]
Please, add a single code that I could run on my own without external dependencies, no firestore, no firebase ect. only keyboard_actions,  you should be able to reproduce the issue in a single file withouth dependencies.

**Comment by jhbiggs** [comment]
Yes, there are no other dependencies.  I commented out the firestore references.  Can you accept material.dart and cupertino.dart?

**Comment by diegoveloper** [comment]
I've just changed this method:

```dart


  Widget _pushSettings() {
    return Scaffold(
        appBar: AppBar(title: Text('Settings')),
        body: Center(
            child: Container(
                child: KeyboardActions(
          config: _buildConfig(context),
          child: ListView(
            padding: const EdgeInsets.all(16.0),
            children: <Widget>[
              showBathOrShowerChoice(),
              Divider(height: 5.0),
              showNameChoice("What shall we call you?", "name", nameTextController, TextInputType.text),
              Divider(height: 5.0),
              showTimeNeededChoice("How much time in minutes do you think you'll need?", "number of minutes",
                  timeNeededTextController, TextInputType.number),
              Divider(height: 5.0),
              Container(
                padding: const EdgeInsets.all(15.0),
                child: Center(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    mainAxisSize: MainAxisSize.min,
                    children: <Widget>[
                      TextField(
                        onChanged: (value) async {
                          setState(() {});
                        },
                        keyboardType: TextInputType.number,
                        focusNode: _nodeText2,
                        decoration: InputDecoration(
                          hintText: "$_prefTimeNeeded" ?? "enter minutes",
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              showLogoutButton(),
              Divider(height: 5.0),
            ],
          ),
        ))));
  }
```

Works fine on iOS

![Simulator Screen Shot - iPhone 8 - 2020-05-28 at 15 11 10](https://user-images.githubusercontent.com/4898256/83188581-8d85a880-a0f5-11ea-8bb3-bdfd813a02bb.png)

**Comment by jhbiggs** [comment]
Nope, still there on my device.  I'll keep looking.  It works fine on a simulator.  Strange.

Thank you for the quick and helpful response!  I have been impressed by your contributions to Flutter.

**Comment by diegoveloper** [comment]
Thanks bro, try to find a way to reproduce the issue and I could help you.

**Comment by jhbiggs** [comment]
Got it!  I had imported the same file twice.  It caused the gap for some reason.  Suggestion after all this:  maybe name your files something clearly different.  keyboard_action.dart and keyboard_actions.dart look quite similar.

**Comment by jhbiggs** [comment]
Ok, really figured it out.  As long as you launch from StatelessWidget, there's no gap.  If you launch from a StatefulWidget tree, it will give the gap.  Strange behavior.

**Comment by diegoveloper** [comment]
that's weird, so you were able to reproduce the issue then.

**Comment by jhbiggs** [comment]
Yes, but only on my own device, an iPhone 7 with current iOS build.  I tried on a simulator iPhone 11, it worked fine with or without the Stateful widget lower down on the tree.

**Comment by kgb16** [comment]
After many attempts, I found that the problem is here: MediaQuery.of (context). viewInsets.bottom 。 When there is a problem, the value here will include the bottom height of safearea.

**Comment by kgb16** [comment]
> Yes, but only on my own device, an iPhone 7 with current iOS build. I tried on a simulator iPhone 11, it worked fine with or without the Stateful widget lower down on the tree.

yes, it worked fine on simulator

**Comment by jhbiggs** [comment]
So, how do we keep the MediaQuery from sending the safe area bottom parameter?  I noticed the same thing.

**Comment by diegoveloper** [comment]
hey guys, don't forget Pull requests are open in case you want to contribute

**Comment by diegoveloper** [comment]
hey guys, could you reproduce the bug on the latest version?

**Comment by rhyscoronado** [comment]
@diegoveloper  I can still reproduce this on the latest version. 

![image](https://user-images.githubusercontent.com/5875039/90622254-72838a00-e247-11ea-9aa9-6723e7fd2a8d.png)

**Comment by diegoveloper** [comment]
Hello, add a minimum sample code to reproduce the issue.

**Comment by Nurgunkalol** [comment]
same here 
![Screenshot_1599385098](https://user-images.githubusercontent.com/20499983/92323123-14410e80-f071-11ea-8190-91281625960f.png)
```
KeyboardActionsConfig _buildConfig(BuildContext context) {
    return KeyboardActionsConfig(
      keyboardActionsPlatform: KeyboardActionsPlatform.ALL,
      keyboardBarColor: Colors.grey[200],
      nextFocus: true,
      actions: [
        KeyboardActionsItem(
          displayDoneButton: false,
          displayActionBar: false,
          displayArrows: false,
          focusNode: _nodeText6,
          footerBuilder: (_) =>
            PreferredSize(
              child: SizedBox(
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: [
                    SizedBox(
                      width: 40,
                      child:
                      RaisedButton(
                        color: Colors.white,
                        onPressed: () {
                          setState(() {
                            _editingController.text += 'ҥ';
                            this.setPosition();
                          });
                        }, 
                        child: Text('ҥ')),
                    ),
                    SizedBox(
                      width: 40,
                      child:
                      RaisedButton(
                        color: Colors.white,
                        onPressed: () {
                          setState(() {
                            _editingController.text += 'ҕ';
                            this.setPosition();
                          });
                        }, child: Text('ҕ')),
                    ),
                    SizedBox(
                      width: 40,
                      child:
                      RaisedButton(
                        color: Colors.white,
                        onPressed: () {
                          setState(() {
                            _editingController.text += 'ө';
                            this.setPosition();
                          });
                        }, child: Text('ө')),
                    ),
                    SizedBox(
                      width: 40,
                      child:
                      RaisedButton(
                        color: Colors.white,
                        onPressed: () {
                          setState(() {
                            _editingController.text += 'һ';
                            this.setPosition();
                          });
                        }, child: Text('һ')),
                    ),
                    SizedBox(
                      width: 40,
                      child:
                      RaisedButton(
                        color: Colors.white,
                        onPressed: () {
                          setState(() {
                            _editingController.text += 'ү';
                            this.setPosition();
                          });
                        },
                        child: Text('ү')
                      )
                    ),
                  ],
                )),
              preferredSize: Size.fromHeight(40)),
        )
      ],
    );
  }
```

...
```
@override
  Widget build(BuildContext context) {
     return KeyboardActions(
      config: _buildConfig(context),
      child:
       Container(
        padding: const EdgeInsets.all(1.0),
        child: Center(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              TextField(
                keyboardType: TextInputType.text,
                controller: _editingController,
                focusNode: _nodeText6,
                decoration: InputDecoration(
                  hintText: "Input Number with Custom Footer",
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

```
> 

emulator GALAXY NEXUS API 27

**Comment by bacr** [comment]
@diegoveloper please see this reproduction sample https://gist.github.com/bacr/bb07e9fb1f7712ff86de82335e287d80

**Comment by diegoveloper** [comment]
Please use a minimum sample code to reproduce the issue

**Comment by DanielYK** [comment]
the prroblem is still there

**Comment by BenjiFarquhar** [comment]
@diegoveloper I just added a BottomNavigationBar to some parts of my app, and I see this issue in those parts.

**Comment by BenjiFarquhar** [comment]
The fix for me is to use `resizeToAvoidBottomInset: true,` on the `Scaffold` that has the `BottomNavigationBar`, and you have to completely stop the app and recompile it, not just hot restart it.

**Comment by xlfdyzcs** [comment]
> In Flutter version 3.7.7 and keyboard_actions version 4.2.0, the same issue still persists.

+1
