### ISSUE TITLE
Background is scrollable and there is no way to configure scroll physics in `BottomAreaAvoider`.

### ISSUE THREAD

**Issue by lzhuor** [diegoveloper/flutter_keyboard_actions#93]
Hi, the `BottomAreaAvoider` is currently scrollable when keyboard is open. I think a better experience or a common alternative people would like to have is to disallow background scrolling when keyboard is focused.

**Comment by diegoveloper** [comment]
Thanks , it's on `dev` now, you can point directly to that branch until I released a new version
