### ISSUE TITLE
How to adapt FloatingActionButtonLocation when showing keyboard action?

### ISSUE THREAD

**Issue by nohli** [diegoveloper/flutter_keyboard_actions#94]
![Simulator Screen Shot - iPhone X - 2020-05-30 at 21 23 37](https://user-images.githubusercontent.com/43643339/83338014-544d6400-a2c0-11ea-94c0-78355cb0a4af.png)

![Simulator Screen Shot - iPhone X - 2020-05-30 at 21 23 35](https://user-images.githubusercontent.com/43643339/83338013-531c3700-a2c0-11ea-8391-8f5adc819609.png)

The first screenshot shows how the FAB location adapts for a normal keyboard, the second screenshot shows that some value is not updated with the additional keyboard actions size.
(probably one of the values used for: https://api.flutter.dev/flutter/material/ScaffoldPrelayoutGeometry-class.html)

How can I make it work as expected?

Second question: How do I set the color to the color of the rest of the keyboard - or (since I could set this myself for each platform/theme:) are the colors the keyboard uses for light/darkmode on ios/android known?

Thanks a lot.

**Comment by diegoveloper** [comment]
Hey, for keyboard theme I think you can try this solution: https://stackoverflow.com/a/57620243/666221

And about the scaffold - fab button, you can try this property : https://github.com/diegoveloper/flutter_keyboard_actions/blob/master/lib/keyboard_actions.dart#L56

`overscroll` , where you can set something like 20 or 40.

Let me know if it works for you.

**Comment by nohli** [comment]
Hi @diegoveloper, thanks for the quick reply!

After adding the overscoll, it still looks the same - the FloatingActionButton does not move upwards to avoid overlapping with your plugin. Am I doing something wrong? Should I declare some offset in the Scaffold?

And regarding the color: I don't want to change the keyboard's color, but want to match the color of your plugin to the default color of the keyboard. Maybe I will just find out the color in photoshop and then set it fitting to the device/theme.

The two things I would like to achieve are that the keyboard inset behaves like a native inset (i.e. the suggestions/ auto-correction bar which you can see in the first screenshot above):
1. The FloatingActionButton is above the inset
2. It has the same color as the rest of the keyboard (which I could do with a workaround)
I think, this should be the standard behavior.

**Comment by diegoveloper** [comment]
Could you add a minimal code to reproduce the issue?

**Comment by nohli** [comment]
@diegoveloper of course :)

```
import 'package:flutter/material.dart';
import 'package:keyboard_actions/keyboard_actions.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: KeyboardActions(
        config: keyboardActionsConfig,
        child: Center(
          child: TextField(
              keyboardType: TextInputType.number,
              focusNode: focusNode,
              textAlign: TextAlign.center),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: Icon(Icons.add),
      ),
    );
  }
}

FocusNode focusNode = FocusNode();

KeyboardActionsConfig keyboardActionsConfig =
    KeyboardActionsConfig(actions: [KeyboardAction(focusNode: focusNode)]);
```

**Comment by diegoveloper** [comment]
I see, the overscroll is handled inside the List (scroll the list), one workaround you can use is using padding, like this :

```
 floatingActionButton: Padding(
        padding: const EdgeInsets.only(bottom: 30.0),
        child: FloatingActionButton(
          onPressed: () {},
          child: Icon(Icons.add),
        ),
      ),
```

Because we don't have control about other UI component outside `KeyboardActions`

**Comment by nohli** [comment]
Okay, thanks @diegoveloper 
 
Can you think of a good place to update a bool when the focusNode comed to focus (and leaves focus), so that I can set an adaptive padding for the FloatingActionButton?

**Comment by diegoveloper** [comment]
Yeah you can do it. Check this : https://stackoverflow.com/a/54907267/666221

**Comment by nohli** [comment]
Thanks a lot!! It's working now.

I kind of copied the iOS color and done button optics, here is the result:

![Simulator Screen Shot - iPhone X - 2020-06-01 at 19 21 15](https://user-images.githubusercontent.com/43643339/83435815-26415e80-a43d-11ea-8b39-71f6bf52e29e.png)

![Simulator Screen Shot - iPhone X - 2020-06-01 at 19 20 59](https://user-images.githubusercontent.com/43643339/83435823-28a3b880-a43d-11ea-989e-7db49c6e030e.png)

```
import 'package:flutter/material.dart';
import 'package:keyboard_actions/keyboard_actions.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
        theme: ThemeData.light(),
        darkTheme: ThemeData.dark(),
      );
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
    focusNode.addListener(() {
      if (mounted)
        setState(() {
          keyboardActionVisible = focusNode.hasFocus;
        });
    });
  }

  @override
  void dispose() {
    focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: KeyboardActions(
        config: keyboardActionsConfig(context),
        child: Center(
          child: TextField(
            keyboardAppearance: Theme.of(context).brightness,
            keyboardType: TextInputType.number,
            textAlign: TextAlign.center,
            focusNode: focusNode,
          ),
        ),
      ),
      floatingActionButton: Padding(
        padding: EdgeInsets.only(bottom: keyboardActionVisible ? 45 : 0),
        child: FloatingActionButton(
          onPressed: () {},
          child: Icon(Icons.add),
        ),
      ),
    );
  }
}

bool keyboardActionVisible = false;

FocusNode focusNode = FocusNode();

KeyboardActionsConfig keyboardActionsConfig(BuildContext context) =>
    KeyboardActionsConfig(
      nextFocus: false,
      keyboardActionsPlatform: KeyboardActionsPlatform.IOS,
      keyboardBarColor: Theme.of(context).brightness == Brightness.dark ?? false
          ? Color.fromRGBO(54, 54, 54, 1)
          // the dark keyboard background color (above) changes with the app's background color
         // for Colors.black it is:
         // Color.fromRGBO(43, 43, 43, 1)
          : Color.fromRGBO(214, 216, 221, 1),
      actions: [
        KeyboardAction(
          displayDoneButton: false,
          focusNode: focusNode,
          toolbarButtons: <Widget Function(FocusNode)>[
            (node) {
              return Center(
                child: Padding(
                  padding: const EdgeInsets.only(right: 7),
                  child: MaterialButton(
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(4)),
                    elevation: 2,
                    onPressed: () => node.unfocus(),
                    color: Color.fromRGBO(0, 122, 255, 1),
                    child: Text(
                      // translate('done'),
                      'done',
                      textScaleFactor: 1,
                      style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w400,
                          color: Colors.white),
                    ),
                  ),
                ),
              );
            }
          ],
        )
      ],
    );
```

**Comment by diegoveloper** [comment]
Nice, I'm glad to help :)
