### ISSUE TITLE
Keyboard not pushing bottom sheet content upwards

### ISSUE THREAD

**Issue by benkashbase** [diegoveloper/flutter_keyboard_actions#95]
Am using this library inside my modal bottom sheet. However, I noticed that on pop up, the keyboard does not push the content upwards, it just covers the content. How do I fix this because it is inconvenient for users.

 padding: EdgeInsets.only(
                  bottom: MediaQuery.of(context).viewInsets.bottom),

Using this code inside my container pushes it up actually but it causes an unwanted top white space above the keyboard.

**Comment by diegoveloper** [comment]
Add a minimal code to reproduce the issue

**Comment by benkashbase** [comment]
this is a link to the gist file:

https://gist.github.com/benkashbase/3d0aa0917583059fe65e153570ca450b

**Comment by benkashbase** [comment]
this is a link to the gist file:

https://gist.github.com/benkashbase/3d0aa0917583059fe65e153570ca450b

**Comment by diegoveloper** [comment]
Did you fix the issue?

**Comment by benkashbase** [comment]
this is a link to the gist file:

https://gist.github.com/benkashbase/3d0aa0917583059fe65e153570ca450b

**Comment by benkashbase** [comment]
nope. I noticed that it doesn't push the content up if I set a height to my container

**Comment by scortumee** [comment]
same problem here. The keyboard overlays the textField

**Comment by diegoveloper** [comment]
Please add minimal code to reproduce the issue,  or check the samples
inside the package, those works very well

**Comment by scortumee** [comment]
![ezgif-3-9571ae27bfc9](https://user-images.githubusercontent.com/18318832/85080644-a296aa00-b17e-11ea-9fde-631d64e945b4.gif)
I tried the first example. I will add the minimal code soon. Above is what is happening. Thanks for your quick response @diegoveloper

**Comment by scortumee** [comment]
Hey @diegoveloper, sorry about the delay. Below is the minimal code to reproduce the issue. Please run it on both android and ios. You will see what is going on. I have noticed the bug appears when TextField is at the bottom of the screen and the keyboard does not push up the TextField properly.

https://gist.github.com/scortumee/5aa651591cb0cd047e9fd11bc95e33c9

keyboard_actions: ^3.2.0
flutter: v1.16
device: iPhone 8

Thanks

**Comment by diegoveloper** [comment]
Did you try declaring `KeyboardActions` as a top of your `ListView` ?

**Comment by scortumee** [comment]
@diegoveloper You mean wrap 'ListView' with 'KeyboardActions'?
In other words, put 'ListView' as a child of 'KeyboardActions'

**Comment by diegoveloper** [comment]
yes

**Comment by scortumee** [comment]
@diegoveloper Thanks, wrapping 'ListView' with 'KeyboardActions' worked! The keyboard pushes the TextField smoothly
