### ISSUE TITLE
error: The method 'KeyboardAction' isn't defined for the type

### ISSUE THREAD

**Issue by dgurudot** [diegoveloper/flutter_keyboard_actions#98]
We have been using flutter_keyboard_actions in our app for quite some time.

After upgrade to recent package (3.3.0) , we are starting to get the following error and reverting back to older version (^3.2.1+1) is not helping.

**Error**: error: The method 'KeyboardAction' isn't defined for the type

**Comment by diegoveloper** [comment]
Yeah, check the changelog, that class was renamed.

**Comment by Tafaching** [comment]
What was the solution this getting same error

**Comment by diegoveloper** [comment]
Check the samples of the package

**Comment by Tafaching** [comment]
Got it thanks @diegoveloper
